import { Injectable, NotFoundException } from "@nestjs/common";
import { and, eq, sql } from "drizzle-orm";
import { discountRules, products, productVariants, createDbClient, withOrgContext, type SparkDb } from "@spark/db";
import { money, toCents, type CreateDiscountRuleInput, type CreateProductInput, type CreateProductVariantInput, type DiscountRule, type DiscountRuleId, type OrgId, type Product, type ProductId, type ProductVariant, type UpdateDiscountRuleInput, type UpdateProductInput } from "@spark/core";
import { DomainEventWriter } from "../../events/application/domain-event-writer.js";
@Injectable()
export class CatalogRepository {
  private readonly db: SparkDb = createDbClient(process.env.DATABASE_URL ?? "");
  constructor(private readonly events: DomainEventWriter) {}
  createProduct(orgId: OrgId, input: CreateProductInput): Promise<{ product: Product; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.insert(products).values({ id: input.id, orgId, sku: input.sku, name: input.name, description: input.description ?? null, price: toCents(input.price), currency: input.currency ?? "BRL", unit: input.unit ?? "un", stock: input.stock ?? null, active: input.active ?? true, tags: input.tags ?? [] }).returning(); if (!row) throw new Error("Product insert returned no row."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "product.created", data: { productId: row.id, name: row.name } }); return { product: toProduct(row), txid }; }); }
  updateProduct(orgId: OrgId, id: ProductId, input: UpdateProductInput): Promise<{ product: Product; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const { price, ...plain } = input; const values = { ...plain, ...(price ? { price: toCents(price) } : {}), updatedAt: new Date() }; const [row] = await tx.update(products).set(values).where(and(eq(products.id, id), eq(products.orgId, orgId))).returning(); if (!row) throw new NotFoundException("Produto não encontrado."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "product.updated", data: { productId: id, fields: Object.keys(input) } }); return { product: toProduct(row), txid }; }); }
  archiveProduct(orgId: OrgId, id: ProductId, archived: boolean): Promise<{ product: Product; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.update(products).set({ deletedAt: archived ? new Date() : null, updatedAt: new Date() }).where(and(eq(products.id, id), eq(products.orgId, orgId))).returning(); if (!row) throw new NotFoundException("Produto não encontrado."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: archived ? "product.archived" : "product.restored", data: { productId: id } }); return { product: toProduct(row), txid }; }); }
  createVariant(orgId: OrgId, input: CreateProductVariantInput): Promise<{ variant: ProductVariant; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.insert(productVariants).values({ id: input.id, orgId, productId: input.productId, sku: input.sku, name: input.name, priceAdjustment: input.priceAdjustment ? toCents(input.priceAdjustment) : 0, stock: input.stock ?? null, active: input.active ?? true }).returning(); if (!row) throw new Error("Variant insert returned no row."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "product.variant_created", data: { productId: input.productId, variantId: row.id } }); return { variant: toVariant(row), txid }; }); }
  createDiscount(orgId: OrgId, input: CreateDiscountRuleInput): Promise<{ discountRule: DiscountRule; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.insert(discountRules).values({ id: input.id, orgId, name: input.name, type: input.type, value: input.value, minimumSubtotal: input.minimumSubtotal ? toCents(input.minimumSubtotal) : 0, startsAt: input.startsAt ? new Date(input.startsAt) : null, endsAt: input.endsAt ? new Date(input.endsAt) : null, active: input.active ?? true }).returning(); if (!row) throw new Error("Discount insert returned no row."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "discount_rule.created", data: { discountRuleId: row.id, name: row.name } }); return { discountRule: toDiscount(row), txid }; }); }
  updateDiscount(orgId: OrgId, id: DiscountRuleId, input: UpdateDiscountRuleInput): Promise<{ discountRule: DiscountRule; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const { minimumSubtotal, startsAt, endsAt, ...plain } = input; const values = { ...plain, ...(minimumSubtotal ? { minimumSubtotal: toCents(minimumSubtotal) } : {}), ...(startsAt !== undefined ? { startsAt: startsAt ? new Date(startsAt) : null } : {}), ...(endsAt !== undefined ? { endsAt: endsAt ? new Date(endsAt) : null } : {}), updatedAt: new Date() }; const [row] = await tx.update(discountRules).set(values).where(and(eq(discountRules.id, id), eq(discountRules.orgId, orgId))).returning(); if (!row) throw new NotFoundException("Regra de desconto não encontrada."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "discount_rule.updated", data: { discountRuleId: id, fields: Object.keys(input) } }); return { discountRule: toDiscount(row), txid }; }); }
}
async function captureTxid(tx: SparkDb): Promise<number> { const rows = await tx.execute<{ txid: string }>(sql`SELECT pg_current_xact_id()::xid::text as txid`); if (!rows[0]) throw new Error("Could not obtain transaction id."); return Number(rows[0].txid); }
function toProduct(row: typeof products.$inferSelect): Product { return { ...row, price: money(row.price), tags: row.tags ?? [], createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), deletedAt: row.deletedAt?.toISOString() ?? null } as Product; }
function toVariant(row: typeof productVariants.$inferSelect): ProductVariant { return { ...row, priceAdjustment: money(row.priceAdjustment), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as ProductVariant; }
function toDiscount(row: typeof discountRules.$inferSelect): DiscountRule { return { ...row, minimumSubtotal: money(row.minimumSubtotal), startsAt: row.startsAt?.toISOString() ?? null, endsAt: row.endsAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as DiscountRule; }
