import { useMemo, useState, type ReactNode } from "react";
import { Button } from "../Button/Button.js";
import s from "./DataTable.module.css";
export interface TableColumn<T> {id:string;label:string;cell:(row:T)=>ReactNode;sortValue?:(row:T)=>string|number;align?:"start"|"end"}
export interface DataTableProps<T> {label:string;rows:readonly T[];columns:readonly TableColumn<T>[];rowKey:(row:T)=>string;actions?:(row:T)=>ReactNode;state?:"ready"|"loading"|"error";onRetry?:()=>void;emptyText?:string}
export function DataTable<T>({label,rows,columns,rowKey,actions,state="ready",onRetry,emptyText="Nenhum registro encontrado"}:DataTableProps<T>){
 const [sort,setSort]=useState<{id:string;direction:1|-1}|null>(null);
 const ordered=useMemo(()=>{const accessor=columns.find(c=>c.id===sort?.id)?.sortValue;if(!accessor||!sort)return rows;return [...rows].sort((a,b)=>{const left=accessor(a),right=accessor(b);return (typeof left==="number"&&typeof right==="number"?left-right:String(left).localeCompare(String(right),"pt-BR",{numeric:true}))*sort.direction;});},[rows,columns,sort]);
 return <div className={s.root}>{state==="loading"?<p role="status">Carregando registros…</p>:state==="error"?<div role="alert"><p>Não foi possível carregar os registros.</p>{onRetry&&<Button variant="secondary" onClick={onRetry}>Tentar novamente</Button>}</div>:<><div className={s.scroll} role="region" aria-label={label} tabIndex={0}><table className={s.table}><caption>{label}</caption><thead><tr>{columns.map(column=><th key={column.id} scope="col" data-align={column.align} aria-sort={column.sortValue?(sort?.id===column.id?(sort.direction===1?"ascending":"descending"):"none"):undefined}>{column.sortValue?<Button size="sm" variant="ghost" onClick={()=>setSort(previous=>({id:column.id,direction:previous?.id===column.id&&previous.direction===1?-1:1}))}>{column.label}{sort?.id===column.id?(sort.direction===1?" ↑":" ↓"):""}</Button>:column.label}</th>)}{actions&&<th scope="col">Ações</th>}</tr></thead><tbody>{ordered.length?ordered.map(row=><tr key={rowKey(row)}>{columns.map(column=><td key={column.id} data-align={column.align}>{column.cell(row)}</td>)}{actions&&<td className={s.actions}>{actions(row)}</td>}</tr>):<tr><td colSpan={columns.length+(actions?1:0)} className={s.empty}>{emptyText}</td></tr>}</tbody></table></div><p className={s.hint}>Em telas estreitas, deslize a tabela para ver todas as colunas.</p></>}</div>;
}
