import { Injectable, NotFoundException } from "@nestjs/common"; import { and, eq, max, sql } from "drizzle-orm"; import { randomBytes } from "node:crypto"; import { createDbClient, pagePublicKeys, pages, pageVersions, withOrgContext, type SparkDb } from "@spark/db"; import { pageVersionId, type CreatePageInput, type OrgId, type Page, type PageId, type UpdatePageInput, type UserId } from "@spark/core"; import { defaultBlock, renderPageDocument } from "@spark/blocks"; import { DomainEventWriter } from "../../events/application/domain-event-writer.js";
@Injectable() export class PagesRepository { private readonly db: SparkDb = createDbClient(process.env.DATABASE_URL ?? ""); constructor(private readonly events: DomainEventWriter) {}
  create(orgId: OrgId, userId: UserId, input: CreatePageInput) { return withOrgContext(this.db, orgId, async (tx) => { const publicKey = randomBytes(24).toString("base64url"); const draftTree = { blocks: [defaultBlock("hero", blockId()), defaultBlock("text", blockId()), defaultBlock("button", blockId())] }; const [row] = await tx.insert(pages).values({ ...input, orgId, publicKey, draftTree, createdBy: userId }).returning(); if (!row) throw new Error("Page insert returned no row."); await tx.insert(pagePublicKeys).values({ publicKey, orgId, pageId: input.id }); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "page.created", data: { pageId: input.id } }); return { page: toPage(row), txid }; }); }
  update(orgId: OrgId, id: PageId, input: UpdatePageInput) { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.update(pages).set({ ...input, status: "draft", updatedAt: new Date() }).where(and(eq(pages.orgId, orgId), eq(pages.id, id))).returning(); if (!row) throw new NotFoundException("Página não encontrada."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "page.updated", data: { pageId: id, fields: Object.keys(input) } }); return { page: toPage(row), txid }; }); }
  publish(orgId: OrgId, userId: UserId, id: PageId) { return withOrgContext(this.db, orgId, async (tx) => { const [page] = await tx.select().from(pages).where(and(eq(pages.orgId, orgId), eq(pages.id, id))).limit(1); if (!page) throw new NotFoundException("Página não encontrada."); const [latest] = await tx.select({ version: max(pageVersions.version) }).from(pageVersions).where(eq(pageVersions.pageId, id)); const version = (latest?.version ?? 0) + 1; const versionId = pageVersionId.create(); const html = renderPageDocument(page.draftTree, page.name); await tx.insert(pageVersions).values({ id: versionId, orgId, pageId: id, version, tree: page.draftTree, html, createdBy: userId }); const [row] = await tx.update(pages).set({ status: "published", publishedVersionId: versionId, publishedAt: new Date(), updatedAt: new Date() }).where(eq(pages.id, id)).returning(); if (!row) throw new Error("Page publish returned no row."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "page.published", data: { pageId: id, version } }); return { page: toPage(row), txid }; }); }
  async publicPage(publicKey: string) { const [lookup] = await this.db.select().from(pagePublicKeys).where(eq(pagePublicKeys.publicKey, publicKey)).limit(1); if (!lookup) throw new NotFoundException("Página indisponível."); return withOrgContext(this.db, lookup.orgId as OrgId, async (tx) => { const [page] = await tx.select().from(pages).where(and(eq(pages.id, lookup.pageId), eq(pages.status, "published"))).limit(1); if (!page?.publishedVersionId) throw new NotFoundException("Página indisponível."); const [version] = await tx.select().from(pageVersions).where(eq(pageVersions.id, page.publishedVersionId)).limit(1); if (!version) throw new NotFoundException("Versão publicada indisponível."); return { name: page.name, html: version.html, publicKey: page.publicKey }; }); }
}
async function captureTxid(tx: SparkDb) { const rows = await tx.execute<{ txid: string }>(sql`SELECT pg_current_xact_id()::xid::text as txid`); return Number(rows[0]?.txid); } function toPage(row: typeof pages.$inferSelect): Page { return { ...row, publishedAt: row.publishedAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as Page; }
function blockId(): string { const value = randomBytes(16); value[6] = ((value[6] ?? 0) & 0x0f) | 0x40; value[8] = ((value[8] ?? 0) & 0x3f) | 0x80; const hex = value.toString("hex"); return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`; }
