import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { useLiveQuery } from "@tanstack/react-db";
import { campaignsControllerCreateAudience, campaignsControllerCreateCampaign, campaignsControllerSend } from "@spark/api-client";
import { audienceId, campaignId, matchesAudience, type Audience, type AudienceFilter, type Campaign } from "@spark/core";
import { ActionCard, ActionCardGroup, ActionModal, Badge, Button, Checkbox, CollectionToolbar, DataTable, EmptyState, Field, Icon, Input, Label, PageHeader, Select, Textarea, notify, type TableColumn } from "@spark/ui-web";
import { getSession } from "../lib/auth.client"; import { requireCapability } from "../lib/route-access.client"; import { getContactsCollection } from "../lib/contacts-collection.client";
import { getAudiencesCollection, getCampaignRecipientsCollection, getCampaignsCollection } from "../lib/campaign-collections.client"; import styles from "./campaigns.module.css";

const LEAD_STATUSES = [{ value: "new", label: "Novo" }, { value: "qualified", label: "Qualificado" }, { value: "customer", label: "Cliente" }, { value: "lost", label: "Perdido" }];
export async function clientLoader() { await requireCapability("campaigns:read"); void Promise.allSettled([getAudiencesCollection().preload(), getCampaignsCollection().preload(), getCampaignRecipientsCollection().preload(), getContactsCollection().preload()]); return null; }
export default function Campaigns() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const audienceView = searchParams.get("view") === "audiences";
  const capabilities = getSession()?.capabilities ?? [];
  const canWrite = capabilities.includes("campaigns:write");
  const canImportContacts = capabilities.includes("contacts:write");
  const canConfigureEmail = capabilities.includes("integrations:manage");
  const { data: audiences, isLoading: audiencesLoading } = useLiveQuery({ query: (q) => q.from({ audiences: getAudiencesCollection() }).orderBy(({ audiences: item }) => item.updatedAt, "desc") });
  const { data: campaigns, isLoading } = useLiveQuery({ query: (q) => q.from({ campaigns: getCampaignsCollection() }).orderBy(({ campaigns: item }) => item.createdAt, "desc") });
  const { data: contacts } = useLiveQuery({ query: (q) => q.from({ contacts: getContactsCollection() }) });
  const [audienceOpen, setAudienceOpen] = useState(false); const [campaignOpen, setCampaignOpen] = useState(false); const [sending, setSending] = useState<string | null>(null);
  const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const [audienceName, setAudienceName] = useState(""); const [description, setDescription] = useState(""); const [operator, setOperator] = useState<"all" | "any">("all"); const [statuses, setStatuses] = useState<string[]>([]); const [tags, setTags] = useState(""); const [minimumScore, setMinimumScore] = useState("");
  const [name, setName] = useState(""); const [audienceIdValue, setAudienceIdValue] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const filter: AudienceFilter = useMemo(() => ({ operator, leadStatuses: statuses, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean), minimumScore: minimumScore === "" ? null : Number(minimumScore) }), [operator, statuses, tags, minimumScore]);
  const previewCount = contacts.filter((contact) => matchesAudience({ ...contact, tags: contact.tags }, filter)).length;
  const audienceById = useMemo(() => new Map<string, Audience>(audiences.map((item) => [item.id, item])), [audiences]);
  const normalizedSearch = search.trim().toLocaleLowerCase("pt-BR");
  const filteredAudiences = audiences.filter((item) => !normalizedSearch || `${item.name} ${item.description ?? ""}`.toLocaleLowerCase("pt-BR").includes(normalizedSearch));
  const filteredCampaigns = campaigns.filter((item) => (statusFilter === "all" || item.status === statusFilter) && (!normalizedSearch || `${item.name} ${item.subject} ${audienceById.get(item.audienceId)?.name ?? ""}`.toLocaleLowerCase("pt-BR").includes(normalizedSearch)));
  const firstRun = audienceView ? audiences.length === 0 && !audiencesLoading && !search : campaigns.length === 0 && !isLoading && !search && statusFilter === "all";
  const columns: TableColumn<Campaign>[] = [
    { id: "name", label: "Campanha", cell: (item) => <div className={styles.primary}><strong>{item.name}</strong><span>{item.subject}</span></div>, sortValue: (item) => item.name },
    { id: "audience", label: "Público", cell: (item) => audienceById.get(item.audienceId)?.name ?? "—", sortValue: (item) => audienceById.get(item.audienceId)?.name ?? "" },
    { id: "delivery", label: "Entrega", cell: (item) => `${item.sentCount}/${item.recipientCount}`, sortValue: (item) => item.sentCount },
    { id: "status", label: "Status", cell: (item) => <Badge tone={item.status === "sent" ? "success" : item.status === "failed" ? "danger" : item.status === "partial" ? "warning" : "neutral"}>{statusLabel(item.status)}</Badge>, sortValue: (item) => item.status },
  ];
  const audienceColumns: TableColumn<Audience>[] = [
    { id: "name", label: "Público", cell: (item) => <div className={styles.primary}><strong>{item.name}</strong><span>{item.description || "Sem descrição"}</span></div>, sortValue: (item) => item.name },
    { id: "contacts", label: "Contatos agora", cell: (item) => contacts.filter((contact) => matchesAudience({ ...contact, tags: contact.tags }, item.filter)).length, sortValue: (item) => contacts.filter((contact) => matchesAudience({ ...contact, tags: contact.tags }, item.filter)).length },
    { id: "updated", label: "Atualizado", cell: (item) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(item.updatedAt)), sortValue: (item) => item.updatedAt },
  ];
  async function createAudience() { const response = await campaignsControllerCreateAudience({ id: audienceId.create(), name: audienceName.trim(), description: description.trim() || null, filter }); notify({ title: "Público criado", description: `${previewCount} contato(s) correspondem agora.`, tone: "success" }); setAudienceIdValue(response.audience.id); setAudienceName(""); setDescription(""); }
  async function createCampaign() { await campaignsControllerCreateCampaign({ id: campaignId.create(), audienceId: audienceIdValue as never, name: name.trim(), subject: subject.trim(), body: body.trim() }); notify({ title: "Campanha criada", description: "A lista de destinatários foi congelada para auditoria.", tone: "success" }); setName(""); setSubject(""); setBody(""); }
  function openCampaign() { setAudienceIdValue(audiences[0]?.id ?? ""); setCampaignOpen(true); }
  async function send(item: Campaign) { setSending(item.id); try { const response = await campaignsControllerSend(item.id); notify({ title: response.campaign.status === "sent" ? "Campanha enviada" : "Envio concluído com ocorrências", description: `${response.campaign.sentCount} enviadas · ${response.campaign.failedCount} falhas · ${response.campaign.suppressedCount} suprimidas`, tone: response.campaign.status === "sent" ? "success" : "warning" }); } finally { setSending(null); } }
  function toggleStatus(value: string, checked: boolean) { setStatuses((current) => checked ? [...current, value] : current.filter((item) => item !== value)); }
  return <div className={styles.page}>
    <PageHeader icon={audienceView ? "team" : "mail"} title={audienceView ? "Públicos" : "Campanhas"} actions={canWrite && !firstRun && !(audienceView ? audiencesLoading : isLoading) ? audienceView ? <Button onClick={() => setAudienceOpen(true)}>Novo público</Button> : audiences.length > 0 ? <Button onClick={openCampaign}>Nova campanha</Button> : <Button onClick={() => setAudienceOpen(true)}>Criar público</Button> : undefined} />
    {firstRun && (audienceView
      ? <EmptyState variant="featured" icon="team" title="Crie seu primeiro público" description="Defina quem deve receber suas campanhas. Os contatos entram automaticamente quando correspondem aos filtros." action={canWrite ? <Button onClick={() => setAudienceOpen(true)}>Criar público</Button> : undefined} />
      : <EmptyState variant="featured" icon="mail" title={audiences.length ? "Prepare sua primeira campanha" : "Comece criando um público"} description={audiences.length ? "Escreva a mensagem e escolha quem deve recebê-la. Você poderá revisar o rascunho antes de enviar." : "Um público organiza os contatos por regras e permite criar sua primeira campanha de e-mail."} action={canWrite ? audiences.length ? <Button onClick={openCampaign}>Nova campanha</Button> : <Button onClick={() => setAudienceOpen(true)}>Criar público</Button> : undefined} />)}
    {!audienceView && firstRun && (canWrite || canImportContacts || canConfigureEmail) && <ActionCardGroup title="Prepare seu primeiro envio">
        {canWrite && <ActionCard icon={audiences.length ? "mail" : "team"} title={audiences.length ? "Escreva a mensagem" : "Escolha o público"} description={audiences.length ? "Crie um rascunho para revisar antes do envio." : "Defina os contatos que devem receber a campanha."} action={<Button variant="secondary" onClick={audiences.length ? openCampaign : () => setAudienceOpen(true)}>{audiences.length ? "Nova campanha" : "Criar público"}</Button>} />}
        {canImportContacts && <ActionCard icon="upload" title="Traga seus contatos" description="Importe sua base para enviar mensagens às pessoas certas." action={<Button variant="secondary" onClick={() => void navigate("/contacts/import")}>Importar contatos</Button>} />}
        {canConfigureEmail && <ActionCard icon="mail" title="Conecte o e-mail" description="Prepare o canal que enviará as mensagens da equipe." action={<Button variant="secondary" onClick={() => void navigate("/integrations")}>Configurar e-mail</Button>} />}
    </ActionCardGroup>}
    {!firstRun && <><CollectionToolbar
      search={<Input aria-label={audienceView ? "Buscar públicos" : "Buscar campanhas"} placeholder={audienceView ? "Buscar público" : "Buscar campanha, assunto ou público"} value={search} startAdornment={<Icon name="search" />} onChange={(event) => setSearch(event.target.value)} />}
      filters={!audienceView ? <Select appearance="filter" label="Filtrar campanhas por situação" value={statusFilter} options={[{ value: "all", label: "Todas as situações" }, { value: "draft", label: "Rascunhos" }, { value: "sending", label: "Em envio" }, { value: "sent", label: "Enviadas" }, { value: "partial", label: "Parciais" }, { value: "failed", label: "Com falha" }]} onValueChange={(value) => setStatusFilter(value ?? "all")} /> : undefined}
      count={`${audienceView ? filteredAudiences.length : filteredCampaigns.length} ${audienceView ? filteredAudiences.length === 1 ? "público" : "públicos" : filteredCampaigns.length === 1 ? "campanha" : "campanhas"}`}
    />
    {audienceView
      ? <DataTable label="Públicos" rows={filteredAudiences} columns={audienceColumns} rowKey={(item) => item.id} rowLabel={(item) => item.name} state={audiencesLoading && !audiences.length ? "loading" : "ready"} emptyText={firstRun ? "Os públicos criados aparecerão nesta tabela." : "Nenhum público encontrado."} />
      : <DataTable label="Histórico de campanhas" rows={filteredCampaigns} columns={columns} rowKey={(item) => item.id} rowLabel={(item) => item.name} state={isLoading && !campaigns.length ? "loading" : "ready"} emptyText="Nenhuma campanha neste filtro." actions={(item) => canWrite && item.status === "draft" ? <Button size="sm" loading={sending === item.id} onClick={() => void send(item)}>Enviar agora</Button> : undefined} />}</>}
    <ActionModal open={audienceOpen} onOpenChange={setAudienceOpen} title="Novo público" confirmLabel="Salvar público" errorText="Informe um nome e filtros válidos." onConfirm={createAudience}><div className={styles.form}><Field><Label>Nome</Label><Input value={audienceName} placeholder="Leads qualificados" onChange={(event) => setAudienceName(event.target.value)} /></Field><Field><Label>Descrição</Label><Input value={description} placeholder="Quem faz parte deste público" onChange={(event) => setDescription(event.target.value)} /></Field><Field><Label>Combinação dos filtros</Label><Select label="Operador dos filtros" value={operator} options={[{ value: "all", label: "Todos os filtros" }, { value: "any", label: "Qualquer filtro" }]} onValueChange={(value) => setOperator((value ?? "all") as "all" | "any")} /></Field><Field><Label>Status do lead</Label><div className={styles.checks}>{LEAD_STATUSES.map((item) => <Checkbox key={item.value} checked={statuses.includes(item.value)} onCheckedChange={(checked) => toggleStatus(item.value, checked === true)}>{item.label}</Checkbox>)}</div></Field><Field><Label>Tags</Label><Input value={tags} placeholder="vip, evento, oportunidade" onChange={(event) => setTags(event.target.value)} /></Field><Field><Label>Score mínimo</Label><Input type="number" min="0" value={minimumScore} placeholder="Sem mínimo" onChange={(event) => setMinimumScore(event.target.value)} /></Field><div className={styles.preview}><strong>{previewCount}</strong><span>contato(s) com e-mail entram neste público agora</span></div></div></ActionModal>
    <ActionModal open={campaignOpen} onOpenChange={setCampaignOpen} title="Nova campanha" confirmLabel="Criar rascunho" errorText="Preencha público, nome, assunto e mensagem." onConfirm={createCampaign}><div className={styles.form}><Field><Label>Público</Label><Select label="Público" value={audienceIdValue} options={audiences.map((item) => ({ value: item.id, label: item.name }))} onValueChange={(value) => setAudienceIdValue(value ?? "")} /></Field><Field><Label>Nome interno</Label><Input value={name} placeholder="Reativação de setembro" onChange={(event) => setName(event.target.value)} /></Field><Field><Label>Assunto</Label><Input value={subject} placeholder="Temos novidades para você" onChange={(event) => setSubject(event.target.value)} /></Field><Field><Label>Mensagem</Label><Textarea rows={10} value={body} placeholder="Olá {{nome}}…" onChange={(event) => setBody(event.target.value)} /></Field></div></ActionModal>
  </div>;
}
function statusLabel(status: Campaign["status"]) { return { draft: "Rascunho", sending: "Enviando", sent: "Enviada", partial: "Parcial", failed: "Falhou" }[status]; }
