import { useMemo, useState } from "react";
import { useSearchParams } from "react-router";
import { useLiveQuery } from "@tanstack/react-db";
import { catalogControllerArchiveProduct, catalogControllerCreateDiscount, catalogControllerCreateProduct, catalogControllerCreateVariant, catalogControllerRestoreProduct, catalogControllerUpdateDiscount, catalogControllerUpdateProduct } from "@spark/api-client";
import { discountRuleId, formatBRL, money, productId, productVariantId, toCents, toDecimal, type DiscountRule, type Money, type Product } from "@spark/core";
import { catalogMoney } from "@spark/data";
import { ActionModal, Badge, Button, DataTable, Field, Icon, Input, Label, MoneyInput, PageHeader, Select, Switch, Tabs, TableIconAction, Textarea, notify, type TableColumn } from "@spark/ui-web";
import { getDiscountRulesCollection, getProductsCollection, getProductVariantsCollection } from "../lib/catalog-collections.client";
import { getSession } from "../lib/auth.client";
import { requireCapability } from "../lib/route-access.client";
import styles from "./catalog.module.css";

export async function clientLoader() { await requireCapability("catalog:read"); void Promise.allSettled([getProductsCollection().preload(), getProductVariantsCollection().preload(), getDiscountRulesCollection().preload()]); return null; }
export default function Catalog() {
  const [searchParams, setSearchParams] = useSearchParams();
  const activeTab = searchParams.get("view") === "discounts" ? "discounts" : "products";
  const session = getSession(); const canWrite = session?.capabilities.includes("catalog:write") ?? false;
  const { data: products, isLoading } = useLiveQuery({ query: (q) => q.from({ products: getProductsCollection() }).orderBy(({ products: item }) => item.name, "asc") });
  const { data: variants } = useLiveQuery({ query: (q) => q.from({ variants: getProductVariantsCollection() }) });
  const { data: discounts } = useLiveQuery({ query: (q) => q.from({ discounts: getDiscountRulesCollection() }).orderBy(({ discounts: item }) => item.createdAt, "desc") });
  const [search, setSearch] = useState(""); const [visibility, setVisibility] = useState("active"); const [productModal, setProductModal] = useState(false); const [variantProduct, setVariantProduct] = useState<Product | null>(null); const [discountModal, setDiscountModal] = useState(false); const [editingProduct, setEditingProduct] = useState<Product | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
  const [sku, setSku] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState<Money | null>(null); const [currency, setCurrency] = useState<"BRL" | "USD">("BRL"); const [unit, setUnit] = useState("un"); const [stock, setStock] = useState("");
  const [variantSku, setVariantSku] = useState(""); const [variantName, setVariantName] = useState(""); const [adjustment, setAdjustment] = useState<Money | null>(money(0)); const [variantStock, setVariantStock] = useState("");
  const [discountName, setDiscountName] = useState(""); const [discountType, setDiscountType] = useState<"percentage" | "fixed_amount">("percentage"); const [percentage, setPercentage] = useState(""); const [fixedAmount, setFixedAmount] = useState<Money | null>(null); const [minimum, setMinimum] = useState<Money | null>(money(0)); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState("");
  const countVariants = useMemo(() => variants.reduce((map, item) => map.set(item.productId, (map.get(item.productId) ?? 0) + 1), new Map<string, number>()), [variants]);
  const shownProducts = products.filter((item) => (visibility === "all" || (visibility === "archived" ? Boolean(item.deletedAt) : !item.deletedAt)) && (!search.trim() || `${item.name} ${item.sku}`.toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR"))));
  const productColumns: TableColumn<Product>[] = [
    { id: "product", label: "Produto", cell: (item) => <div><strong>{item.name}</strong><small className={styles.secondary}>{item.sku}</small></div>, sortValue: (item) => item.name },
    { id: "price", label: "Preço", cell: (item) => formatMoney(catalogMoney(item.price), item.currency), sortValue: (item) => toCents(catalogMoney(item.price)) },
    { id: "stock", label: "Estoque", cell: (item) => item.stock === null ? "Sem controle" : `${item.stock} ${item.unit}`, sortValue: (item) => item.stock ?? Number.MAX_SAFE_INTEGER },
    { id: "variants", label: "Variações", cell: (item) => countVariants.get(item.id) ?? 0, sortValue: (item) => countVariants.get(item.id) ?? 0 },
    { id: "status", label: "Status", cell: (item) => <Badge tone={item.deletedAt || !item.active ? "neutral" : "success"}>{item.deletedAt ? "Arquivado" : item.active ? "Ativo" : "Inativo"}</Badge>, sortValue: (item) => item.deletedAt ? 0 : item.active ? 2 : 1 },
  ];
  const discountColumns: TableColumn<DiscountRule>[] = [
    { id: "name", label: "Regra", cell: (item) => <strong>{item.name}</strong>, sortValue: (item) => item.name },
    { id: "value", label: "Desconto", cell: (item) => item.type === "percentage" ? `${(item.value / 100).toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%` : formatBRL(money(item.value)), sortValue: (item) => item.value },
    { id: "minimum", label: "Pedido mínimo", cell: (item) => formatBRL(catalogMoney(item.minimumSubtotal)), sortValue: (item) => toCents(catalogMoney(item.minimumSubtotal)) },
    { id: "period", label: "Período", cell: (item) => period(item), sortValue: (item) => item.startsAt ?? "" },
    { id: "active", label: "Status", cell: (item) => <Badge tone={item.active ? "success" : "neutral"}>{item.active ? "Ativa" : "Inativa"}</Badge>, sortValue: (item) => Number(item.active) },
  ];
  function openProduct(item?: Product) { setEditingProduct(item ?? null); setSku(item?.sku ?? ""); setName(item?.name ?? ""); setDescription(item?.description ?? ""); setPrice(item ? catalogMoney(item.price) : null); setCurrency(item?.currency ?? "BRL"); setUnit(item?.unit ?? "un"); setStock(item?.stock === null || item?.stock === undefined ? "" : String(item.stock)); setProductModal(true); }
  async function saveProduct() { if (!name.trim() || !sku.trim() || !price) throw new Error("MISSING_PRODUCT"); const input = { sku: sku.trim(), name: name.trim(), description: description.trim() || null, price: toCents(price), currency, unit: unit.trim() || "un", stock: stock === "" ? null : Number(stock), active: true, tags: [] }; if (editingProduct) await catalogControllerUpdateProduct(editingProduct.id, input); else await catalogControllerCreateProduct({ id: productId.create(), ...input }); notify({ title: editingProduct ? "Produto atualizado" : "Produto criado", description: name, tone: "success" }); }
  async function saveVariant() { if (!variantProduct || !variantName.trim() || !variantSku.trim()) throw new Error("MISSING_VARIANT"); await catalogControllerCreateVariant({ id: productVariantId.create(), productId: variantProduct.id, sku: variantSku.trim(), name: variantName.trim(), priceAdjustment: toCents(adjustment ?? money(0)), stock: variantStock === "" ? null : Number(variantStock), active: true }); notify({ title: "Variação criada", description: variantName, tone: "success" }); setVariantSku(""); setVariantName(""); }
  async function saveDiscount() { if (!discountName.trim()) throw new Error("MISSING_DISCOUNT"); const value = discountType === "percentage" ? Math.round(Number(percentage.replace(",", ".")) * 100) : toCents(fixedAmount ?? money(0)); if (value <= 0 || (discountType === "percentage" && value > 10000)) throw new Error("INVALID_DISCOUNT"); await catalogControllerCreateDiscount({ id: discountRuleId.create(), name: discountName.trim(), type: discountType, value, minimumSubtotal: toCents(minimum ?? money(0)), startsAt: startsAt ? new Date(startsAt).toISOString() : null, endsAt: endsAt ? new Date(endsAt).toISOString() : null, active: true }); notify({ title: "Regra de desconto criada", description: discountName, tone: "success" }); }
  async function toggleProduct(item: Product) { setBusyId(item.id); try { if (item.deletedAt) await catalogControllerRestoreProduct(item.id); else await catalogControllerArchiveProduct(item.id); } finally { setBusyId(null); } }
  async function toggleDiscount(item: DiscountRule) { setBusyId(item.id); try { await catalogControllerUpdateDiscount(item.id, { active: !item.active }); } finally { setBusyId(null); } }
  const productsPanel = <div className={styles.panel}><div className={styles.toolbar}><Input aria-label="Buscar produtos" placeholder="Buscar por nome ou SKU" value={search} startAdornment={<Icon name="search" />} onChange={(event) => setSearch(event.target.value)} /><Select label="Visibilidade" value={visibility} options={[{ value: "active", label: "Ativos" }, { value: "archived", label: "Arquivados" }, { value: "all", label: "Todos" }]} onValueChange={(value) => setVisibility(value ?? "active")} />{canWrite && <Button onClick={() => openProduct()}>Novo produto</Button>}</div><DataTable label="Produtos" rows={shownProducts} columns={productColumns} rowKey={(item) => item.id} rowLabel={(item) => item.name} state={isLoading && !products.length ? "loading" : "ready"} emptyText="Nenhum produto neste filtro." actions={(item) => canWrite ? <><TableIconAction label="Editar produto" icon={<Icon name="file" />} onClick={() => openProduct(item)} /><TableIconAction label="Adicionar variação" icon={<Icon name="plus" />} onClick={() => setVariantProduct(item)} /><Button size="sm" variant="ghost" loading={busyId === item.id} onClick={() => void toggleProduct(item)}>{item.deletedAt ? "Restaurar" : "Arquivar"}</Button></> : undefined} /></div>;
  const discountsPanel = <div className={styles.panel}><div className={styles.toolbar}><span className={styles.explanation}>Defina descontos por valor ou percentual, com período e pedido mínimo.</span>{canWrite && <Button onClick={() => setDiscountModal(true)}>Nova regra</Button>}</div><DataTable label="Regras de desconto" rows={discounts} columns={discountColumns} rowKey={(item) => item.id} rowLabel={(item) => item.name} state="ready" emptyText="Nenhuma regra de desconto." actions={(item) => canWrite ? <Switch checked={item.active} disabled={busyId === item.id} onCheckedChange={() => void toggleDiscount(item)}>Ativa</Switch> : undefined} /></div>;
  return <div className={styles.page}><PageHeader title={activeTab === "discounts" ? "Ofertas e descontos" : "Produtos"} description={activeTab === "discounts" ? "Gerencie as condições comerciais aplicadas às vendas." : "Organize produtos, preços, variações e estoque."} /><Tabs label="Áreas do catálogo" value={activeTab} onValueChange={(value) => setSearchParams({ view: value })} items={[{ value: "products", label: `Produtos (${products.length})`, content: productsPanel }, { value: "discounts", label: `Ofertas e descontos (${discounts.length})`, content: discountsPanel }]} />
    <ActionModal open={productModal} onOpenChange={setProductModal} title={editingProduct ? "Editar produto" : "Novo produto"} confirmLabel={editingProduct ? "Salvar alterações" : "Criar produto"} errorText="Revise nome, SKU e preço." onConfirm={saveProduct}><div className={styles.form}><div className={styles.columns}><Field><Label>Nome</Label><Input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field><Label>SKU</Label><Input value={sku} onChange={(event) => setSku(event.target.value)} /></Field></div><Field><Label>Descrição</Label><Textarea value={description} onChange={(event) => setDescription(event.target.value)} /></Field><div className={styles.columns}><Field><Label>Preço</Label><MoneyInput label="Preço" currency={currency} value={price} onValueChange={setPrice} /></Field><Field><Label>Moeda</Label><Select label="Moeda" value={currency} options={[{ value: "BRL", label: "Real brasileiro" }, { value: "USD", label: "Dólar americano" }]} onValueChange={(value) => setCurrency(value === "USD" ? "USD" : "BRL")} /></Field></div><div className={styles.columns}><Field><Label>Unidade</Label><Input value={unit} onChange={(event) => setUnit(event.target.value)} /></Field><Field><Label>Estoque</Label><Input type="number" min="0" value={stock} placeholder="Sem controle" onChange={(event) => setStock(event.target.value)} /></Field></div></div></ActionModal>
    <ActionModal open={Boolean(variantProduct)} onOpenChange={(open) => { if (!open) setVariantProduct(null); }} title={`Nova variação${variantProduct ? ` de ${variantProduct.name}` : ""}`} confirmLabel="Criar variação" errorText="Revise nome e SKU." onConfirm={saveVariant}><div className={styles.form}><div className={styles.columns}><Field><Label>Nome</Label><Input value={variantName} placeholder="Ex.: Azul / G" onChange={(event) => setVariantName(event.target.value)} /></Field><Field><Label>SKU</Label><Input value={variantSku} onChange={(event) => setVariantSku(event.target.value)} /></Field></div><div className={styles.columns}><Field><Label>Acréscimo no preço</Label><MoneyInput label="Acréscimo" currency={variantProduct?.currency ?? "BRL"} value={adjustment} onValueChange={setAdjustment} /></Field><Field><Label>Estoque</Label><Input type="number" min="0" value={variantStock} placeholder="Sem controle" onChange={(event) => setVariantStock(event.target.value)} /></Field></div></div></ActionModal>
    <ActionModal open={discountModal} onOpenChange={setDiscountModal} title="Nova regra de desconto" confirmLabel="Criar regra" errorText="Revise o valor e o período." onConfirm={saveDiscount}><div className={styles.form}><Field><Label>Nome</Label><Input value={discountName} onChange={(event) => setDiscountName(event.target.value)} /></Field><div className={styles.columns}><Field><Label>Tipo</Label><Select label="Tipo de desconto" value={discountType} options={[{ value: "percentage", label: "Percentual" }, { value: "fixed_amount", label: "Valor fixo" }]} onValueChange={(value) => setDiscountType(value === "fixed_amount" ? "fixed_amount" : "percentage")} /></Field>{discountType === "percentage" ? <Field><Label>Percentual</Label><Input type="number" min="0.01" max="100" step="0.01" value={percentage} endAdornment="%" onChange={(event) => setPercentage(event.target.value)} /></Field> : <Field><Label>Valor</Label><MoneyInput label="Valor do desconto" value={fixedAmount} onValueChange={setFixedAmount} /></Field>}</div><Field><Label>Subtotal mínimo</Label><MoneyInput label="Subtotal mínimo" value={minimum} onValueChange={setMinimum} /></Field><div className={styles.columns}><Field><Label>Começa em</Label><Input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></Field><Field><Label>Termina em</Label><Input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></Field></div></div></ActionModal>
  </div>;
}
function formatMoney(value: Money, currency: "BRL" | "USD"): string { return new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(toDecimal(value)); }
function period(item: DiscountRule): string { if (!item.startsAt && !item.endsAt) return "Sempre"; const format = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)); return `${item.startsAt ? format(item.startsAt) : "Agora"} – ${item.endsAt ? format(item.endsAt) : "Sem fim"}`; }
