import { useEffect, useState } from "react"; import { useLiveQuery } from "@tanstack/react-db"; import { useNavigate, useParams } from "react-router"; import { pagesControllerPublish, pagesControllerUpdate } from "@spark/api-client"; import type { PageBlock, PageTree } from "@spark/core"; import { BLOCK_CATALOG, defaultBlock, renderPageDocument } from "@spark/blocks"; import { Badge, Button, EmptyState, Field, Icon, Input, Label, PageHeader, Select, Skeleton, Textarea, notify, type IconName } from "@spark/ui-web"; import { getPagesCollection } from "../lib/pages-collections.client"; import { getSession } from "../lib/auth.client"; import { requireCapability } from "../lib/route-access.client"; import styles from "./page-builder.module.css";
const BLOCK_ICONS: Record<PageBlock["type"], IconName> = { hero: "star", text: "text", image: "image", button: "right", spacer: "minus" };
export async function clientLoader() { await requireCapability("pages:read"); void getPagesCollection().preload().catch(() => undefined); return null; }
export default function PageBuilder() { const { pageId } = useParams(); const navigate = useNavigate(); const canWrite = getSession()?.capabilities.includes("pages:write") ?? false; const { data: pages, isLoading } = useLiveQuery({ query: (q) => q.from({ pages: getPagesCollection() }) }); const page = pages.find((item) => item.id === pageId); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [tree, setTree] = useState<PageTree>({ blocks: [] }); const [selectedId, setSelectedId] = useState<string | null>(null); const [panelMode, setPanelMode] = useState<"blocks" | "structure" | "properties" | "page">("blocks"); const [mobileView, setMobileView] = useState<"editor" | "preview">("editor"); const [saving, setSaving] = useState(false); useEffect(() => { if (!page) return; setName(page.name); setSlug(page.slug); setTree(page.draftTree); setSelectedId(page.draftTree.blocks[0]?.id ?? null); }, [page]); if (!page) return <div className={styles.page}><PageHeader title="Editor de página" />{isLoading ? <div className={styles.loading} role="status" aria-label="Carregando página"><Skeleton /><Skeleton /><Skeleton /></div> : <EmptyState icon="file" title="Página não encontrada" description="Esta página não está mais disponível ou você não tem acesso a ela." action={<Button onClick={() => navigate("/pages")}>Ver páginas</Button>} />}</div>; const selected = tree.blocks.find((block) => block.id === selectedId) ?? null;
  function add(type: PageBlock["type"]) { const block = defaultBlock(type, crypto.randomUUID()) as PageBlock; setTree((current) => ({ blocks: [...current.blocks, block] })); setSelectedId(block.id); setPanelMode("properties"); }
  function patchSelected(props: Record<string, unknown>) { if (!selected) return; setTree((current) => ({ blocks: current.blocks.map((block) => block.id === selected.id ? { ...block, props: { ...block.props, ...props } } as PageBlock : block) })); }
  function move(index: number, offset: number) { setTree((current) => { const target = index + offset; if (target < 0 || target >= current.blocks.length) return current; const blocks = [...current.blocks]; const [block] = blocks.splice(index, 1); if (!block) return current; blocks.splice(target, 0, block); return { blocks }; }); }
  async function save() { setSaving(true); try { await pagesControllerUpdate(page!.id, { name: name.trim(), slug: slug.trim(), draftTree: tree }); notify({ title: "Rascunho salvo", tone: "success" }); } finally { setSaving(false); } }
  async function publish() { setSaving(true); try { await pagesControllerUpdate(page!.id, { name: name.trim(), slug: slug.trim(), draftTree: tree }); const response = await pagesControllerPublish(page!.id); notify({ title: "Página publicada", description: `Versão disponível em /p/${response.page.publicKey}`, tone: "success" }); } finally { setSaving(false); } }
  return <div className={styles.page}>
    <PageHeader title={page.name} actions={<div className={styles.actions}>
      <Button variant="ghost" onClick={() => navigate("/pages")}>Voltar</Button>
      {page.status === "published" && <Button variant="secondary" onClick={() => window.open(`/p/${page.publicKey}`, "_blank", "noopener,noreferrer")}>Abrir publicada</Button>}
      {canWrite && <Button variant="secondary" loading={saving} onClick={() => void save()}>Salvar</Button>}
      {canWrite && <Button loading={saving} onClick={() => void publish()}>Publicar</Button>}
    </div>} />
    <div className={styles.mobileViewSwitch} role="group" aria-label="Visualização da página">
      <Button size="sm" variant={mobileView === "editor" ? "secondary" : "ghost"} shape="rounded" aria-pressed={mobileView === "editor"} onClick={() => setMobileView("editor")}>Editar</Button>
      <Button size="sm" variant={mobileView === "preview" ? "secondary" : "ghost"} shape="rounded" aria-pressed={mobileView === "preview"} onClick={() => setMobileView("preview")}>Prévia</Button>
    </div>
    <div className={styles.workspace} data-mobile-view={mobileView}>
      <aside className={styles.toolPanel} aria-label="Ferramentas da página">
        <nav className={styles.panelTabs} aria-label="Área de edição">
          {([['blocks', 'Blocos'], ['structure', 'Estrutura'], ['properties', 'Propriedades'], ['page', 'Página']] as const).map(([mode, label]) => <Button key={mode} size="sm" variant={panelMode === mode ? "secondary" : "ghost"} shape="rounded" aria-pressed={panelMode === mode} onClick={() => setPanelMode(mode)}>{label}</Button>)}
        </nav>
        {panelMode === "blocks" && <section className={styles.panelSection}>
          <h2>Adicionar bloco</h2><p>Escolha um bloco para inserir no fim da página.</p>
          <div className={styles.catalog}>{BLOCK_CATALOG.map((item) => <Button key={item.type} className={styles.catalogItem} variant="ghost" shape="rounded" icon={<Icon name={BLOCK_ICONS[item.type]} />} trailingIcon={<Icon name="plus" />} disabled={!canWrite} onClick={() => add(item.type)}><span className={styles.catalogCopy}><strong>{item.label}</strong><small>{item.description}</small></span></Button>)}</div>
        </section>}
        {panelMode === "structure" && <section className={styles.panelSection}>
          <h2>Estrutura</h2><p>Selecione, reorganize ou remova blocos.</p>
          <div className={styles.blockList}>{tree.blocks.map((block, index) => <div key={block.id} className={selectedId === block.id ? styles.blockActive : styles.block}>
            <Button variant="ghost" onClick={() => { setSelectedId(block.id); setPanelMode("properties"); }}>{BLOCK_CATALOG.find((item) => item.type === block.type)?.label ?? block.type}</Button>
            {canWrite && <div><Button iconOnly size="sm" variant="ghost" aria-label="Subir" disabled={index === 0} onClick={() => move(index, -1)}><Icon name="up" /></Button><Button iconOnly size="sm" variant="ghost" aria-label="Descer" disabled={index === tree.blocks.length - 1} onClick={() => move(index, 1)}><Icon name="chevron" /></Button><Button iconOnly size="sm" variant="ghost" aria-label="Remover" onClick={() => setTree((current) => ({ blocks: current.blocks.filter((item) => item.id !== block.id) }))}><Icon name="trash" /></Button></div>}
          </div>)}</div>
          {!tree.blocks.length && <span className={styles.empty}>Adicione um bloco para começar.</span>}
        </section>}
        {panelMode === "properties" && <section className={styles.panelSection}>
          <h2>Propriedades</h2><p>{selected ? `Editando ${BLOCK_CATALOG.find((item) => item.type === selected.type)?.label ?? selected.type}` : "Selecione um bloco na estrutura."}</p>
          {selected ? <BlockFields block={selected} onChange={patchSelected} /> : <span className={styles.empty}>Nenhum bloco selecionado.</span>}
        </section>}
        {panelMode === "page" && <section className={styles.panelSection}>
          <h2>Dados da página</h2><p>Defina o nome interno e o endereço público.</p>
          <div className={styles.fields}><Field><Label>Nome</Label><Input value={name} disabled={!canWrite} onChange={(event) => setName(event.target.value)} /></Field><Field><Label>Endereço</Label><Input value={slug} disabled={!canWrite} onChange={(event) => setSlug(event.target.value)} /></Field></div>
        </section>}
      </aside>
      <section className={styles.preview} aria-label="Prévia da página">
        <div className={styles.previewHeader}><span>Prévia</span><Badge tone={page.status === "published" ? "success" : "neutral"}>{page.status === "published" ? "Publicada" : "Rascunho"}</Badge></div>
        <iframe title="Prévia da página" srcDoc={renderPageDocument(tree, name || page.name)} />
      </section>
    </div>
  </div>; }

function BlockFields({ block, onChange }: { block: PageBlock; onChange: (props: Record<string, unknown>) => void }) { if (block.type === "hero") return <div className={styles.fields}><Field><Label>Sobretítulo</Label><Input value={block.props.eyebrow} onChange={(event) => onChange({ eyebrow: event.target.value })} /></Field><Field><Label>Título</Label><Input value={block.props.title} onChange={(event) => onChange({ title: event.target.value })} /></Field><Field><Label>Texto</Label><Textarea value={block.props.text} onChange={(event) => onChange({ text: event.target.value })} /></Field><Align value={block.props.align} onChange={(align) => onChange({ align })} /></div>; if (block.type === "text") return <div className={styles.fields}><Field><Label>Título</Label><Input value={block.props.heading} onChange={(event) => onChange({ heading: event.target.value })} /></Field><Field><Label>Texto</Label><Textarea rows={8} value={block.props.text} onChange={(event) => onChange({ text: event.target.value })} /></Field><Align value={block.props.align} onChange={(align) => onChange({ align })} /></div>; if (block.type === "image") return <div className={styles.fields}><Field><Label>URL da imagem</Label><Input value={block.props.url} onChange={(event) => onChange({ url: event.target.value })} /></Field><Field><Label>Texto alternativo</Label><Input value={block.props.alt} onChange={(event) => onChange({ alt: event.target.value })} /></Field></div>; if (block.type === "button") return <div className={styles.fields}><Field><Label>Texto</Label><Input value={block.props.label} onChange={(event) => onChange({ label: event.target.value })} /></Field><Field><Label>Destino</Label><Input value={block.props.url} onChange={(event) => onChange({ url: event.target.value })} /></Field><Align value={block.props.align} onChange={(align) => onChange({ align })} /></div>; return <Field><Label>Tamanho</Label><Select label="Tamanho do espaço" value={block.props.size} options={[{ value: "small", label: "Pequeno" }, { value: "medium", label: "Médio" }, { value: "large", label: "Grande" }]} onValueChange={(value) => onChange({ size: value ?? "medium" })} /></Field>; }
function Align({ value, onChange }: { value: "left" | "center"; onChange: (value: "left" | "center") => void }) { return <Field><Label>Alinhamento</Label><Select label="Alinhamento" value={value} options={[{ value: "left", label: "Esquerda" }, { value: "center", label: "Centro" }]} onValueChange={(next) => onChange((next ?? "left") as "left" | "center")} /></Field>; }
