import { CUSTOM_FIELD_TYPES, CUSTOM_FIELD_TYPE_LABELS, CUSTOM_FIELD_ENTITIES, CUSTOM_FIELD_ENTITY_LABELS } from "@spark/core";
import { useState } from "react"; import { useLiveQuery } from "@tanstack/react-db"; import { settingsControllerArchive, settingsControllerCreate } from "@spark/api-client"; import { customFieldDefinitionId, type CustomFieldDefinition, type CustomFieldEntity, type CustomFieldType } from "@spark/core"; import { ActionModal, Badge, Button, Checkbox, CollectionToolbar, DataTable, EmptyState, Field, Icon, Input, Label, MenuButton, MenuItem, PageFrame, PageHeader, RecordIdentity, Select, notify, type TableColumn } from "@spark/ui-web"; import { getCustomFieldsCollection } from "../lib/custom-fields-collection.client"; import { requireCapability } from "../lib/route-access.client"; import styles from "./settings.module.css";
const ENTITY_OPTIONS = CUSTOM_FIELD_ENTITIES.map((value) => ({ value, label: CUSTOM_FIELD_ENTITY_LABELS[value] })); const TYPE_OPTIONS = CUSTOM_FIELD_TYPES.map((value) => ({ value, label: CUSTOM_FIELD_TYPE_LABELS[value] }));
export async function clientLoader() { await requireCapability("settings:manage"); void getCustomFieldsCollection().preload().catch(() => undefined); return null; }
export default function Settings() { const { data: fields, isLoading } = useLiveQuery({ query: (q) => q.from({ fields: getCustomFieldsCollection() }).orderBy(({ fields: item }) => item.createdAt, "desc") }); const [open, setOpen] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [search, setSearch] = useState(""); const [entityFilter, setEntityFilter] = useState("all"); const [label, setLabel] = useState(""); const [key, setKey] = useState(""); const [entityType, setEntityType] = useState<CustomFieldEntity>("contact"); const [type, setType] = useState<CustomFieldType>("text"); const [required, setRequired] = useState(false); const [options, setOptions] = useState("");
  const searchTerm = search.trim().toLocaleLowerCase("pt-BR");
  const shownFields = fields.filter((item) => (entityFilter === "all" || item.entityType === entityFilter) && (!searchTerm || `${item.label} ${item.key}`.toLocaleLowerCase("pt-BR").includes(searchTerm)));
  const columns: TableColumn<CustomFieldDefinition>[] = [{ id: "label", label: "Campo", cell: (item) => <RecordIdentity icon="file" title={item.label} subtitle={item.key} subtitleVariant="code" />, sortValue: (item) => item.label }, { id: "entity", label: "Registro", cell: (item) => labelFor(ENTITY_OPTIONS, item.entityType), sortValue: (item) => item.entityType }, { id: "type", label: "Tipo", cell: (item) => labelFor(TYPE_OPTIONS, item.type), sortValue: (item) => item.type }, { id: "required", label: "Regra", cell: (item) => <Badge tone={item.required ? "info" : "neutral"}>{item.required ? "Obrigatório" : "Opcional"}</Badge>, sortValue: (item) => item.required ? 1 : 0 }, { id: "status", label: "Status", cell: (item) => <Badge tone={item.archivedAt ? "neutral" : "success"}>{item.archivedAt ? "Arquivado" : "Ativo"}</Badge>, sortValue: (item) => item.archivedAt ?? "" }];
  async function create() { const normalizedOptions = options.split(",").map((item) => item.trim()).filter(Boolean); await settingsControllerCreate({ id: customFieldDefinitionId.create(), entityType, key: key.trim(), label: label.trim(), type, required, options: normalizedOptions }); notify({ title: "Campo criado", description: `${label} já está disponível nos registros.`, tone: "success" }); setLabel(""); setKey(""); setOptions(""); setRequired(false); }
  async function toggle(item: CustomFieldDefinition) { setBusy(item.id); try { await settingsControllerArchive(item.id, { archived: !item.archivedAt }); notify({ title: item.archivedAt ? "Campo restaurado" : "Campo arquivado", tone: "success" }); } finally { setBusy(null); } }
  const firstRun = fields.length === 0 && !isLoading && !search && entityFilter === "all";
  return <PageFrame width="content" className={styles.page}>
    <PageHeader icon="file" eyebrow="Administração" title="Campos personalizados" description="Adapte os cadastros às informações que sua equipe precisa acompanhar." actions={fields.length > 0 ? <Button onClick={() => setOpen(true)}>Novo campo</Button> : undefined} />
    {firstRun && <EmptyState variant="featured" icon="file" title="Adapte seus cadastros" description="Crie campos para guardar as informações específicas das pessoas, empresas e negócios." action={<Button onClick={() => setOpen(true)}>Novo campo</Button>} />}
    {!firstRun && <CollectionToolbar search={<Input aria-label="Buscar campos personalizados" placeholder="Buscar nome ou chave" value={search} startAdornment={<Icon name="search" />} onChange={(event) => setSearch(event.target.value)} />} filters={<Select appearance="filter" label="Filtrar campos por registro" value={entityFilter} options={[{ value: "all", label: "Todos os registros" }, ...ENTITY_OPTIONS]} onValueChange={(value) => setEntityFilter(value ?? "all")} />} count={isLoading ? "Carregando campos…" : `${shownFields.length} ${shownFields.length === 1 ? "campo" : "campos"}`} />}
    {!firstRun && <DataTable label="Campos personalizados" rows={shownFields} columns={columns} rowKey={(item) => item.id} rowLabel={(item) => item.label} state={isLoading && !fields.length ? "loading" : "ready"} emptyText="Nenhum campo encontrado." actions={(item) => <MenuButton size="sm" variant="ghost" shape="rounded" iconOnly indicator={false} icon={<Icon name="more" />} aria-label={"Ações de " + item.label} loading={busy === item.id} menu={<MenuItem onClick={() => void toggle(item)}>{item.archivedAt ? "Restaurar" : "Arquivar"}</MenuItem>} />} />}
    <ActionModal open={open} onOpenChange={setOpen} title="Novo campo personalizado" confirmLabel="Criar campo" errorText="Revise o nome, a chave e as opções." onConfirm={create}>
      <div className={styles.form}>
        <Field><Label>Registro</Label><Select label="Tipo de registro" value={entityType} options={ENTITY_OPTIONS} onValueChange={(value) => setEntityType((value ?? "contact") as CustomFieldEntity)} /></Field>
        <Field><Label>Nome visível</Label><Input value={label} placeholder="Número de funcionários" onChange={(event) => { const next = event.target.value; setLabel(next); if (!key) setKey(slugKey(next)); }} /></Field>
        <Field><Label>Chave técnica</Label><Input value={key} placeholder="numero_funcionarios" onChange={(event) => setKey(slugKey(event.target.value))} /></Field>
        <Field><Label>Tipo</Label><Select label="Tipo do campo" value={type} options={TYPE_OPTIONS} onValueChange={(value) => setType((value ?? "text") as CustomFieldType)} /></Field>
        {(type === "single_select" || type === "multi_select") && <Field><Label>Opções separadas por vírgula</Label><Input value={options} placeholder="Pequena, Média, Grande" onChange={(event) => setOptions(event.target.value)} /></Field>}
        <Checkbox checked={required} onCheckedChange={(checked) => setRequired(checked === true)}>Preenchimento obrigatório</Checkbox>
      </div>
    </ActionModal>
  </PageFrame>;
}
function labelFor(options: Array<{ value: string; label: string }>, value: string) { return options.find((item) => item.value === value)?.label ?? value; } function slugKey(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""); }
