import { Injectable, NotFoundException } from "@nestjs/common"; import { and, eq, sql } from "drizzle-orm"; import { createDbClient, customFieldDefinitions, customFieldOptions, withOrgContext, type SparkDb } from "@spark/db"; import type { CreateCustomFieldInput, CustomFieldDefinition, CustomFieldDefinitionId, OrgId, UserId } from "@spark/core"; import { DomainEventWriter } from "../../events/application/domain-event-writer.js";
@Injectable() export class CustomFieldsRepository { private readonly db: SparkDb = createDbClient(process.env.DATABASE_URL ?? ""); constructor(private readonly events: DomainEventWriter) {}
  create(orgId: OrgId, userId: UserId, input: CreateCustomFieldInput) { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.insert(customFieldDefinitions).values({ ...input, orgId, createdBy: userId }).returning(); if (!row) throw new Error("Custom field insert returned no row.");
    // As opções viram linhas (ADR-0035) — é delas que o relatório e o filtro leem.
    if (input.options.length > 0) await tx.insert(customFieldOptions).values(input.options.map((value, index) => ({ orgId, fieldId: row.id, value, label: value, sortOrder: index })));
    const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "custom_field.created", data: { fieldId: input.id, entityType: input.entityType, key: input.key } }); return { field: toField(row), txid }; }); }
  archive(orgId: OrgId, id: CustomFieldDefinitionId, archived: boolean) { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.update(customFieldDefinitions).set({ archivedAt: archived ? new Date() : null, updatedAt: new Date() }).where(and(eq(customFieldDefinitions.orgId, orgId), eq(customFieldDefinitions.id, id))).returning(); if (!row) throw new NotFoundException("Campo personalizado não encontrado."); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "custom_field.archived", data: { fieldId: id, archived } }); return { field: toField(row), txid }; }); }
}
async function captureTxid(tx: SparkDb) { const rows = await tx.execute<{ txid: string }>(sql`SELECT pg_current_xact_id()::xid::text as txid`); return Number(rows[0]?.txid); }
function toField(row: typeof customFieldDefinitions.$inferSelect): CustomFieldDefinition { return { ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), archivedAt: row.archivedAt?.toISOString() ?? null } as CustomFieldDefinition; }
