CREATE TABLE lead_forms (id uuid PRIMARY KEY, org_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, title text NOT NULL, description text, public_key text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')), fields jsonb NOT NULL DEFAULT '[]'::jsonb, submit_label text NOT NULL DEFAULT 'Enviar', success_message text NOT NULL DEFAULT 'Recebemos seus dados. Obrigado!', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX lead_forms_org_status_idx ON lead_forms (org_id, status); ALTER TABLE lead_forms ENABLE ROW LEVEL SECURITY; CREATE POLICY lead_forms_isolation_by_org ON lead_forms FOR ALL TO app_user USING (org_id = current_setting('app.current_org_id', true)::uuid);
CREATE TABLE lead_form_public_keys (public_key text PRIMARY KEY, org_id uuid NOT NULL REFERENCES organizations(id), form_id uuid NOT NULL REFERENCES lead_forms(id) ON DELETE CASCADE);
CREATE TABLE form_submissions (id uuid PRIMARY KEY, org_id uuid NOT NULL REFERENCES organizations(id), form_id uuid NOT NULL REFERENCES lead_forms(id), contact_id uuid NOT NULL REFERENCES contacts(id), values jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX form_submissions_org_form_created_idx ON form_submissions (org_id, form_id, created_at DESC); ALTER TABLE form_submissions ENABLE ROW LEVEL SECURITY; CREATE POLICY form_submissions_isolation_by_org ON form_submissions FOR ALL TO app_user USING (org_id = current_setting('app.current_org_id', true)::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON lead_forms, form_submissions TO app_user; GRANT SELECT ON lead_form_public_keys TO app_user;
ALTER PUBLICATION electric_publication_default ADD TABLE lead_forms, form_submissions;
UPDATE permission_groups SET capabilities = capabilities || '["forms:read", "forms:write"]'::jsonb, updated_at = now() WHERE name IN ('Proprietário','Administrador','Gerente','Agente') AND NOT capabilities @> '["forms:read", "forms:write"]'::jsonb;
UPDATE permission_groups SET capabilities = capabilities || '["forms:read"]'::jsonb, updated_at = now() WHERE name = 'Visualizador' AND NOT capabilities @> '["forms:read"]'::jsonb;
