import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { and, eq, or, sql } from "drizzle-orm";
import { randomBytes } from "node:crypto";
import { contacts, createDbClient, formSubmissions, identities, leadFormPublicKeys, leadForms, withOrgContext, type SparkDb } from "@spark/db";
import { contactId, email as normalizeEmail, identityId, leadFormId, mappedLeadValue, orgId, phone as normalizePhone, validateLeadFormValues, type ContactId, type CreateLeadFormInput, type LeadForm, type LeadFormField, type LeadFormId, type OrgId, type SubmitLeadFormInput, type UpdateLeadFormInput } from "@spark/core";
import { DomainEventWriter } from "../../events/application/domain-event-writer.js";
import { LeadFormFieldsRepository } from "./lead-form-fields.repository.js";
const DEFAULT_FIELDS: LeadFormField[] = [{ id: "name", label: "Nome", type: "text", mapping: "name", required: true, options: [] }, { id: "email", label: "E-mail", type: "email", mapping: "email", required: true, options: [] }];
@Injectable()
export class FormsRepository {
  private readonly db: SparkDb = createDbClient(process.env.DATABASE_URL ?? ""); constructor(private readonly events: DomainEventWriter, private readonly fieldsRepository: LeadFormFieldsRepository) {}
  create(orgId: OrgId, input: CreateLeadFormInput): Promise<{ form: LeadForm; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.insert(leadForms).values({ id: input.id, orgId, name: input.name, title: input.title, description: input.description ?? null, publicKey: randomBytes(24).toString("base64url"), fields: input.fields ?? DEFAULT_FIELDS, submitLabel: input.submitLabel ?? "Enviar", successMessage: input.successMessage ?? "Recebemos seus dados. Obrigado!" }).returning(); if (!row) throw new Error("Form insert returned no row."); await this.fieldsRepository.replaceFields(tx, orgId, row.id, input.fields ?? DEFAULT_FIELDS); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "form.created", data: { formId: row.id, name: row.name } }); return { form: toForm(row), txid }; }); }
  update(orgId: OrgId, id: LeadFormId, input: UpdateLeadFormInput): Promise<{ form: LeadForm; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.update(leadForms).set({ ...input, updatedAt: new Date() }).where(and(eq(leadForms.id, id), eq(leadForms.orgId, orgId))).returning(); if (!row) throw new NotFoundException("Formulário não encontrado."); if (input.fields !== undefined) await this.fieldsRepository.replaceFields(tx, orgId, row.id, input.fields); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: "form.updated", data: { formId: id, fields: Object.keys(input) } }); return { form: toForm(row), txid }; }); }
  setPublished(orgId: OrgId, id: LeadFormId, published: boolean): Promise<{ form: LeadForm; txid: number }> { return withOrgContext(this.db, orgId, async (tx) => { const [row] = await tx.update(leadForms).set({ status: published ? "published" : "draft", updatedAt: new Date() }).where(and(eq(leadForms.id, id), eq(leadForms.orgId, orgId))).returning(); if (!row) throw new NotFoundException("Formulário não encontrado."); if (published) await tx.insert(leadFormPublicKeys).values({ publicKey: row.publicKey, orgId, formId: row.id }).onConflictDoNothing(); else await tx.delete(leadFormPublicKeys).where(eq(leadFormPublicKeys.publicKey, row.publicKey)); const txid = await captureTxid(tx); await this.events.append(tx, { orgId, type: published ? "form.published" : "form.unpublished", data: { formId: id } }); return { form: toForm(row), txid }; }); }
  async publicForm(publicKey: string): Promise<LeadForm> { const route = await this.resolve(publicKey); return withOrgContext(this.db, route.orgId, async (tx) => { const [row] = await tx.select().from(leadForms).where(and(eq(leadForms.id, route.formId), eq(leadForms.orgId, route.orgId), eq(leadForms.status, "published"))).limit(1); if (!row) throw new NotFoundException("Formulário indisponível."); return toForm(row, await this.fieldsRepository.fieldsOf(tx, row.id)); }); }
  async submit(publicKey: string, input: SubmitLeadFormInput): Promise<{ successMessage: string; contactId: ContactId | null }> { const form = await this.publicForm(publicKey); if (input.website) return { successMessage: form.successMessage, contactId: null }; try { validateLeadFormValues(form.fields, input.values); } catch (cause) { throw new BadRequestException(cause instanceof Error ? cause.message : "Dados inválidos."); } const rawEmail = mappedLeadValue(form.fields, input.values, "email"); const rawPhone = mappedLeadValue(form.fields, input.values, "phone"); let parsedEmail: string | null = null; let parsedPhone: string | null = null; try { parsedEmail = rawEmail ? normalizeEmail(rawEmail) : null; parsedPhone = rawPhone ? normalizePhone(rawPhone) : null; } catch { throw new BadRequestException("E-mail ou telefone inválido."); } const name = mappedLeadValue(form.fields, input.values, "name") ?? parsedEmail ?? parsedPhone ?? "Novo lead"; return withOrgContext(this.db, form.orgId, async (tx) => { const identityMatch = parsedEmail && parsedPhone ? or(eq(contacts.email, parsedEmail), eq(contacts.phone, parsedPhone)) : parsedEmail ? eq(contacts.email, parsedEmail) : parsedPhone ? eq(contacts.phone, parsedPhone) : undefined; const existing = identityMatch ? await tx.select({ id: contacts.id }).from(contacts).where(and(eq(contacts.orgId, form.orgId), identityMatch)).limit(1) : []; let leadId = existing[0]?.id as ContactId | undefined; if (!leadId) { leadId = contactId.create(); await tx.insert(contacts).values({ id: leadId, orgId: form.orgId, name, email: parsedEmail, phone: parsedPhone, source: `form:${form.id}` }); if (parsedEmail) await tx.insert(identities).values({ id: identityId.create(), orgId: form.orgId, contactId: leadId, channel: "email", externalValue: parsedEmail }).onConflictDoNothing(); if (parsedPhone) await tx.insert(identities).values({ id: identityId.create(), orgId: form.orgId, contactId: leadId, channel: "phone", externalValue: parsedPhone }).onConflictDoNothing(); } await tx.insert(formSubmissions).values({ id: input.id, orgId: form.orgId, formId: form.id, contactId: leadId, values: input.values }); await this.fieldsRepository.writeSubmissionValues(tx, form.orgId, input.id, form.id, input.values); await this.events.append(tx, { orgId: form.orgId, contactId: leadId, type: "form.submitted", data: { formId: form.id, submissionId: input.id } }); return { successMessage: form.successMessage, contactId: leadId }; }); }
  private async resolve(publicKey: string): Promise<{ orgId: OrgId; formId: LeadFormId }> { const rows = await this.db.select().from(leadFormPublicKeys).where(eq(leadFormPublicKeys.publicKey, publicKey)).limit(1); if (!rows[0]) throw new NotFoundException("Formulário indisponível."); return { orgId: orgId.from(rows[0].orgId), formId: leadFormId.from(rows[0].formId) }; }
}
async function captureTxid(tx: SparkDb): Promise<number> { const rows = await tx.execute<{ txid: string }>(sql`SELECT pg_current_xact_id()::xid::text as txid`); if (!rows[0]) throw new Error("Could not obtain transaction id."); return Number(rows[0].txid); }
/* O desenho vem de `lead_form_fields` (ADR-0035); a coluna jsonb ainda
 * existe enquanto a migração termina, e serve só de reserva para um
 * formulário criado antes de a tabela existir. */
function toForm(row: typeof leadForms.$inferSelect, fields?: LeadFormField[]): LeadForm {
  return { ...row, fields: fields && fields.length > 0 ? fields : row.fields ?? [], createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } as LeadForm;
}
