import type { Meta, StoryObj } from "@storybook/react-vite";
import { MenuButton, MenuItem, MenuSeparator, SplitButton } from "./Menu.js";
import { Icon } from "../Icon/Icon.js";
const meta: Meta<typeof MenuButton> = { title: "Componentes/Menu", component: MenuButton };
export default meta;
type Story = StoryObj<typeof MenuButton>;
const options = <><MenuItem>Enviar e fechar</MenuItem><MenuSeparator /><MenuItem>Agendar envio</MenuItem></>;
export const Default: Story = { args: { children: "Mais opções", menu: options, variant: "secondary" } };
export const SoTexto: Story = { args: { children: "Opções", menu: options, variant: "ghost", indicator: false } };
export const TextoComIcone: Story = { args: { children: "Atribuir", menu: options, icon: <Icon name="user" />, variant: "secondary" } };
export const Dividido: Story = { render: () => <SplitButton menu={options} menuLabel="Opções de envio">Enviar</SplitButton> };
export const DivididoRetangular: Story = { render: () => <SplitButton shape="rounded" variant="secondary" menu={options} menuLabel="Opções de salvar">Salvar</SplitButton> };
export const DivididoCarregando: Story = { render: () => <SplitButton loading menu={options}>Enviando</SplitButton> };
