import { useState } from "react";
import { Button } from "../Button/Button.js";
import { Modal, ModalTrigger, ModalContent, ModalClose, ModalColumns, ModalColumn } from "../Modal/Modal.js";
import { ActionModal } from "../Modal/ActionModal.js";
import { Popover, PopoverContent, PopoverTrigger } from "../Popover/Popover.js";
import { NotificationList, type NotificationEntry } from "../Notification/Notification.js";
import { notify, dismissNotification } from "../Notification/Toast.js";
import { InlineEdit } from "../InlineEdit/InlineEdit.js";
import { Input } from "../Input/Input.js";
import styles from "./Catalog.module.css";
export function OverlayExamples(){
  const [confirm,setConfirm]=useState(false);const [fail,setFail]=useState(false);const [completed,setCompleted]=useState(0);
  const [search,setSearch]=useState("");
  const [name,setName]=useState("Proposta comercial");const [note,setNote]=useState("");const [popover,setPopover]=useState(false);
  const [items,setItems]=useState<NotificationEntry[]>([{id:"1",title:"Nova conversa atribuída",description:"A equipe de atendimento atribuiu uma conversa a você.",unread:true},{id:"2",title:"Integração precisa de atenção",description:"Revise a conexão para retomar a sincronização.",tone:"warning",unread:true}]);
  return <>
    <section className={styles.card}><h2>Toasts e notificações</h2><div className={styles.rows}><div className={styles.row}>{(["info","success","warning","error"] as const).map((tone,index)=><Button key={tone} variant="secondary" onClick={()=>notify({title:["Nova atualização","Alterações salvas","Conexão instável","Falha ao salvar"][index] ?? "Aviso",tone,description:"Mensagem configurável pela aplicação."})}>{["Informação","Sucesso","Atenção","Erro"][index]}</Button>)}<Button variant="secondary" onClick={()=>notify({title:"Item arquivado",actions:<Button size="sm" onClick={()=>{dismissNotification("undo");notify({title:"Ação desfeita",tone:"success"});}}>Desfazer</Button>},{id:"undo",duration:Infinity})}>Toast com ação</Button></div><NotificationList items={items} onRead={id=>setItems(previous=>previous.map(item=>item.id===id?{...item,unread:false}:item))} onDismiss={id=>setItems(previous=>previous.filter(item=>item.id!==id))} /></div></section>
    <section className={styles.card}><h2>Popover com edição</h2><Popover open={popover} onOpenChange={setPopover}><PopoverTrigger render={<Button variant="secondary">Adicionar observação</Button>} /><PopoverContent title="Observação"><Input aria-label="Observação" value={note} onChange={e=>setNote(e.target.value)} placeholder="Escreva uma observação" /><div className={styles.row}><Button variant="ghost" onClick={()=>setPopover(false)}>Cancelar</Button><Button onClick={()=>{setPopover(false);notify({title:"Observação salva",description:note,tone:"success"});}}>Salvar</Button></div></PopoverContent></Popover></section>
    <section className={styles.card}><h2>Modal com ação e recuperação</h2><div className={styles.row}><Button onClick={()=>{setFail(false);setConfirm(true);}}>Confirmar ação</Button><Button variant="secondary" onClick={()=>{setFail(true);setConfirm(true);}}>Experimentar falha</Button></div><p role="status">Ações concluídas: {completed}</p><ActionModal open={confirm} onOpenChange={setConfirm} title="Concluir atividade?" confirmLabel="Concluir" onConfirm={()=>{if(fail){setFail(false);return Promise.reject(new Error("Falha simulada"));}setCompleted(n=>n+1);notify({title:"Atividade concluída",tone:"success"});}}><p>A primeira tentativa do exemplo de falha mantém a janela aberta. Tente novamente para concluir.</p></ActionModal></section>
    <section className={styles.card}><h2>Modais de trabalho · CRM</h2><div className={styles.row}>{([2,3] as const).map(columns=><Modal key={columns}><ModalTrigger render={<Button variant="secondary">Modal de {columns} colunas</Button>} /><ModalContent title="Detalhes do negócio" description="Composição reutilizável de campos, atividades e contexto." size={columns===3?"workspace":"wide"} footer={<ModalClose render={<Button>Concluir revisão</Button>} />}><ModalColumns><ModalColumn title="Dados do negócio"><InlineEdit label="Título do negócio" value={name} onSave={setName} /><p>Cliente: Empresa exemplo</p><p>Etapa: Proposta</p></ModalColumn><ModalColumn title="Atividades"><Input aria-label="Pesquisar atividades" placeholder="Pesquisar atividades" value={search} onChange={e=>setSearch(e.target.value)} /><NotificationList items={[{id:"call",title:"Ligação realizada",description:"Contato inicial registrado."},{id:"proposal",title:"Proposta enviada",description:"Aguardando retorno do cliente."}].filter(item=>item.title.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")))} /></ModalColumn>{columns===3 && <ModalColumn title="Contexto e relacionamento"><p>Responsável: Maria</p><p>Origem: Instagram</p><InlineEdit label="Observação do negócio" value={note} onSave={setNote} placeholder="Adicionar observação" /></ModalColumn>}</ModalColumns></ModalContent></Modal>)}</div></section>
  </>;
}
