import { useState } from "react";
import { DataTable, type TableColumn } from "../DataTable/DataTable.js";
import { Input } from "../Input/Input.js";
import { Button } from "../Button/Button.js";
import { MenuButton, MenuItem } from "../Menu/Menu.js";
import { TableIconAction } from "../DataTable/TableActions.js";
import { Icon } from "../Icon/Icon.js";
import { Modal, ModalContent } from "../Modal/Modal.js";
import s from "./Catalog.module.css";
type Row={id:string;name:string;email:string;team:string};
const initial:Row[]=[{id:"1",name:"Maria",email:"maria@exemplo.com",team:"Atendimento"},{id:"2",name:"João",email:"joao@exemplo.com",team:"Vendas"},{id:"3",name:"Ana",email:"ana@exemplo.com",team:"Sucesso do cliente"}];
const columns:TableColumn<Row>[]=[{id:"name",label:"Nome",cell:r=>r.name,sortValue:r=>r.name},{id:"email",label:"E-mail",cell:r=>r.email},{id:"team",label:"Equipe",cell:r=>r.team,sortValue:r=>r.team}];
export function TableExamples(){const [selected,setSelected]=useState<Row|null>(null);const [rows,setRows]=useState(initial);const [query,setQuery]=useState("");const [message,setMessage]=useState("");return <section id="catalog-tables" className={s.card}><h2>Tabelas responsivas</h2><p>Ações por ícone, menu com texto ou só chevron e seta para expandir detalhes.</p><div className={s.rows}><DataTable label="Tabela simples" rows={initial} columns={columns} rowKey={r=>r.id}/><Input aria-label="Pesquisar na tabela" placeholder="Pesquisar nome ou e-mail" value={query} onChange={e=>setQuery(e.target.value)}/><DataTable label="Tabela com ações" rows={rows.filter(row=>`${row.name} ${row.email}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))} columns={columns} rowKey={r=>r.id} rowLabel={r=>r.name} renderExpanded={row=><><strong>{row.name}</strong><p>{row.email}</p><p>Equipe: {row.team}</p></>} actions={row=><><TableIconAction label={`Abrir ${row.name}`} icon={<Icon name="eye"/>} onClick={()=>setSelected(row)}/><MenuButton size="sm" variant="ghost" shape="rounded" iconOnly={row.id!=="1"} indicator={false} icon={row.id!=="1"?<Icon name="chevron"/>:undefined} aria-label={`Mais opções de ${row.name}`} menu={<><MenuItem onClick={()=>setSelected(row)}>Ver detalhes</MenuItem><MenuItem onClick={()=>{setRows(previous=>previous.filter(item=>item.id!==row.id));setMessage(`${row.name} removido desta demonstração.`);}}>Remover da lista</MenuItem></>}>{row.id==="1"?<>Ações <Icon name="chevron"/></>:null}</MenuButton></>}/><p role="status">{message}</p><Button variant="secondary" onClick={()=>{setRows(initial);setQuery("");setMessage("");}}>Restaurar exemplo</Button><DataTable label="Tabela vazia" rows={[]} columns={columns} rowKey={r=>r.id}/></div><Modal open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><ModalContent title={selected?.name??"Detalhes"}><p>{selected?.email}</p><p>Equipe: {selected?.team}</p></ModalContent></Modal></section>;}
