import { sql } from "drizzle-orm";
import { index, pgPolicy, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

import { APP_ROLE } from "../roles.js";
import { idColumn } from "./_helpers.js";
import { contacts } from "./contacts.js";
import { organizations } from "./organizations.js";
export const leadForms = pgTable("lead_forms", { id: idColumn(), orgId: uuid("org_id").notNull().references(() => organizations.id), name: text("name").notNull(), title: text("title").notNull(), description: text("description"), publicKey: text("public_key").notNull(), status: text("status").notNull().default("draft"), submitLabel: text("submit_label").notNull().default("Enviar"), successMessage: text("success_message").notNull().default("Recebemos seus dados. Obrigado!"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("lead_forms_public_key_idx").on(table.publicKey), index("lead_forms_org_status_idx").on(table.orgId, table.status), pgPolicy("lead_forms_isolation_by_org", { for: "all", to: APP_ROLE, using: sql`${table.orgId} = current_setting('app.current_org_id', true)::uuid` })]).enableRLS();
export const leadFormPublicKeys = pgTable("lead_form_public_keys", { publicKey: text("public_key").primaryKey(), orgId: uuid("org_id").notNull().references(() => organizations.id), formId: uuid("form_id").notNull().references(() => leadForms.id, { onDelete: "cascade" }) });
export const formSubmissions = pgTable("form_submissions", { id: idColumn(), orgId: uuid("org_id").notNull().references(() => organizations.id), formId: uuid("form_id").notNull().references(() => leadForms.id), contactId: uuid("contact_id").notNull().references(() => contacts.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [index("form_submissions_org_form_created_idx").on(table.orgId, table.formId, table.createdAt), pgPolicy("form_submissions_isolation_by_org", { for: "all", to: APP_ROLE, using: sql`${table.orgId} = current_setting('app.current_org_id', true)::uuid` })]).enableRLS();
