/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Spark API
 * Contrato gerado dos controllers — ver docs/adr/0004-contrato-openapi-primeiro.md
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { sparkHttpClient } from './http-client';
export interface UserDto {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  supabaseUserId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /** @minLength 1 */
  email: string;
  /** @nullable */
  avatarUrl: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
  /**
     * @nullable
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
  desativadoEm: string | null;
}

export type CreateContactDtoCustomFields = {[key: string]: unknown};

export interface CreateContactDto {
  /** @minLength 1 */
  id: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minLength 1
     * @nullable
     */
  email?: string | null;
  /**
     * @minLength 1
     * @nullable
     */
  telefone?: string | null;
  /**
     * @minimum 0
     * @maximum 100
     */
  score?: number;
  customFields?: CreateContactDtoCustomFields;
  tags?: string[];
}

export type CreateContactResponseDtoContactCustomFields = {[key: string]: unknown};

export type CreateContactResponseDtoContact = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minLength 1
     * @nullable
     */
  email: string | null;
  /**
     * @minLength 1
     * @nullable
     */
  telefone: string | null;
  /**
     * @minimum 0
     * @maximum 100
     */
  score?: number;
  customFields?: CreateContactResponseDtoContactCustomFields;
  tags?: string[];
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
  /**
     * @nullable
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
  excluidoEm: string | null;
};

export interface CreateContactResponseDto {
  contact: CreateContactResponseDtoContact;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export interface CreatePipelineDto {
  /** @minLength 1 */
  id: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  padrao?: boolean;
}

export type CreatePipelineResponseDtoPipeline = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  padrao?: boolean;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
  /**
     * @nullable
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
  arquivadoEm: string | null;
};

export interface CreatePipelineResponseDto {
  pipeline: CreatePipelineResponseDtoPipeline;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export interface CreateStageDto {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  pipelineId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  ordem: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  probabilidade?: number;
}

export type CreateStageResponseDtoStage = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  pipelineId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  ordem: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  probabilidade?: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
  /**
     * @nullable
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
  arquivadoEm: string | null;
};

export interface CreateStageResponseDto {
  stage: CreateStageResponseDtoStage;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export interface RenameStageDto {
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
}

export type RenameStageResponseDtoStage = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  pipelineId: string;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  ordem: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  probabilidade?: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
  /**
     * @nullable
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$
     */
  arquivadoEm: string | null;
};

export interface RenameStageResponseDto {
  stage: RenameStageResponseDtoStage;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export type CreateDealDtoStatus = typeof CreateDealDtoStatus[keyof typeof CreateDealDtoStatus];


export const CreateDealDtoStatus = {
  aberto: 'aberto',
  ganho: 'ganho',
  perdido: 'perdido',
} as const;

export interface CreateDealDto {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  pipelineId: string;
  /** @minLength 1 */
  stageId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId?: string | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  valor: number;
  status?: CreateDealDtoStatus;
  dataFechamentoEsperada?: string | null;
  /**
     * @maxLength 500
     * @nullable
     */
  motivoPerda?: string | null;
}

export type CreateDealResponseDtoDealStatus = typeof CreateDealResponseDtoDealStatus[keyof typeof CreateDealResponseDtoDealStatus];


export const CreateDealResponseDtoDealStatus = {
  aberto: 'aberto',
  ganho: 'ganho',
  perdido: 'perdido',
} as const;

export type CreateDealResponseDtoDeal = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  pipelineId: string;
  /** @minLength 1 */
  stageId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId: string | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  valor: number;
  status?: CreateDealResponseDtoDealStatus;
  dataFechamentoEsperada: string | null;
  /**
     * @maxLength 500
     * @nullable
     */
  motivoPerda: string | null;
  criadoEm: string;
  atualizadoEm: string;
  excluidoEm: string | null;
};

export interface CreateDealResponseDto {
  deal: CreateDealResponseDtoDeal;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export interface MoveDealDto {
  /** @minLength 1 */
  stageId: string;
}

export type MoveDealResponseDtoDealStatus = typeof MoveDealResponseDtoDealStatus[keyof typeof MoveDealResponseDtoDealStatus];


export const MoveDealResponseDtoDealStatus = {
  aberto: 'aberto',
  ganho: 'ganho',
  perdido: 'perdido',
} as const;

export type MoveDealResponseDtoDeal = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  pipelineId: string;
  /** @minLength 1 */
  stageId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId: string | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  valor: number;
  status?: MoveDealResponseDtoDealStatus;
  dataFechamentoEsperada: string | null;
  /**
     * @maxLength 500
     * @nullable
     */
  motivoPerda: string | null;
  criadoEm: string;
  atualizadoEm: string;
  excluidoEm: string | null;
};

export interface MoveDealResponseDto {
  deal: MoveDealResponseDtoDeal;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export type CloseDealDtoStatus = typeof CloseDealDtoStatus[keyof typeof CloseDealDtoStatus];


export const CloseDealDtoStatus = {
  ganho: 'ganho',
  perdido: 'perdido',
} as const;

export interface CloseDealDto {
  status: CloseDealDtoStatus;
  /**
     * @maxLength 500
     * @nullable
     */
  motivoPerda?: string | null;
}

export type CloseDealResponseDtoDealStatus = typeof CloseDealResponseDtoDealStatus[keyof typeof CloseDealResponseDtoDealStatus];


export const CloseDealResponseDtoDealStatus = {
  aberto: 'aberto',
  ganho: 'ganho',
  perdido: 'perdido',
} as const;

export type CloseDealResponseDtoDeal = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /** @minLength 1 */
  pipelineId: string;
  /** @minLength 1 */
  stageId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId: string | null;
  /**
     * @minLength 1
     * @maxLength 200
     */
  nome: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  valor: number;
  status?: CloseDealResponseDtoDealStatus;
  dataFechamentoEsperada: string | null;
  /**
     * @maxLength 500
     * @nullable
     */
  motivoPerda: string | null;
  criadoEm: string;
  atualizadoEm: string;
  excluidoEm: string | null;
};

export interface CloseDealResponseDto {
  deal: CloseDealResponseDtoDeal;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export type CreateActivityDtoTipo = typeof CreateActivityDtoTipo[keyof typeof CreateActivityDtoTipo];


export const CreateActivityDtoTipo = {
  tarefa: 'tarefa',
  ligacao: 'ligacao',
  reuniao: 'reuniao',
  email: 'email',
} as const;

export interface CreateActivityDto {
  /** @minLength 1 */
  id: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId?: string | null;
  /**
     * @minLength 1
     * @nullable
     */
  dealId?: string | null;
  tipo: CreateActivityDtoTipo;
  /**
     * @minLength 1
     * @maxLength 200
     */
  titulo: string;
  /**
     * @maxLength 2000
     * @nullable
     */
  notas?: string | null;
  dataHora: string;
}

export type CreateActivityResponseDtoActivityTipo = typeof CreateActivityResponseDtoActivityTipo[keyof typeof CreateActivityResponseDtoActivityTipo];


export const CreateActivityResponseDtoActivityTipo = {
  tarefa: 'tarefa',
  ligacao: 'ligacao',
  reuniao: 'reuniao',
  email: 'email',
} as const;

export type CreateActivityResponseDtoActivity = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId: string | null;
  /**
     * @minLength 1
     * @nullable
     */
  dealId: string | null;
  tipo: CreateActivityResponseDtoActivityTipo;
  /**
     * @minLength 1
     * @maxLength 200
     */
  titulo: string;
  /**
     * @maxLength 2000
     * @nullable
     */
  notas: string | null;
  dataHora: string;
  concluida?: boolean;
  concluidaEm: string | null;
  criadoEm: string;
  atualizadoEm: string;
};

export interface CreateActivityResponseDto {
  activity: CreateActivityResponseDtoActivity;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

export interface CompleteActivityDto {
  concluida: boolean;
}

export type CompleteActivityResponseDtoActivityTipo = typeof CompleteActivityResponseDtoActivityTipo[keyof typeof CompleteActivityResponseDtoActivityTipo];


export const CompleteActivityResponseDtoActivityTipo = {
  tarefa: 'tarefa',
  ligacao: 'ligacao',
  reuniao: 'reuniao',
  email: 'email',
} as const;

export type CompleteActivityResponseDtoActivity = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  orgId: string;
  /**
     * @minLength 1
     * @nullable
     */
  contactId: string | null;
  /**
     * @minLength 1
     * @nullable
     */
  dealId: string | null;
  tipo: CompleteActivityResponseDtoActivityTipo;
  /**
     * @minLength 1
     * @maxLength 200
     */
  titulo: string;
  /**
     * @maxLength 2000
     * @nullable
     */
  notas: string | null;
  dataHora: string;
  concluida?: boolean;
  concluidaEm: string | null;
  criadoEm: string;
  atualizadoEm: string;
};

export interface CompleteActivityResponseDto {
  activity: CompleteActivityResponseDtoActivity;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  txid: number;
}

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const meControllerMe = (

 signal?: AbortSignal
) => {


      return sparkHttpClient<UserDto>(
      {url: `/v1/me`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }




export const getMeControllerMeQueryKey = () => {
    return [
    `/v1/me`
    ] as const;
    }


export const getMeControllerMeQueryOptions = <TData = Awaited<ReturnType<typeof meControllerMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeControllerMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof meControllerMe>>> = ({ signal }) => meControllerMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof meControllerMe>>>
export type MeControllerMeQueryError = unknown


export function useMeControllerMe<TData = Awaited<ReturnType<typeof meControllerMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerMe<TData = Awaited<ReturnType<typeof meControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meControllerMe>>,
          TError,
          Awaited<ReturnType<typeof meControllerMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeControllerMe<TData = Awaited<ReturnType<typeof meControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeControllerMe<TData = Awaited<ReturnType<typeof meControllerMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof meControllerMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeControllerMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const contactsControllerCreate = (
    createContactDto: CreateContactDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CreateContactResponseDto>(
      {url: `/v1/contacts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContactDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getContactsControllerCreateMutationKey = () => ['contactsControllerCreate'] as const;

export const getContactsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactsControllerCreate>>, TError,ContactsControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof contactsControllerCreate>>, TError,ContactsControllerCreateMutationVariables, TContext> => {

const mutationKey = getContactsControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactsControllerCreate>>, ContactsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  contactsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ContactsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof contactsControllerCreate>>>
    export type ContactsControllerCreateMutationBody = CreateContactDto
    export type ContactsControllerCreateMutationError = unknown
    export type ContactsControllerCreateMutationVariables = {data: CreateContactDto}

    export const useContactsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactsControllerCreate>>, TError,ContactsControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactsControllerCreate>>,
        TError,
        ContactsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getContactsControllerCreateMutationOptions(options), queryClient);
    }

export const pipelinesControllerCreate = (
    createPipelineDto: CreatePipelineDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CreatePipelineResponseDto>(
      {url: `/v1/pipelines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPipelineDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getPipelinesControllerCreateMutationKey = () => ['pipelinesControllerCreate'] as const;

export const getPipelinesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelinesControllerCreate>>, TError,PipelinesControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof pipelinesControllerCreate>>, TError,PipelinesControllerCreateMutationVariables, TContext> => {

const mutationKey = getPipelinesControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pipelinesControllerCreate>>, PipelinesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  pipelinesControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PipelinesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof pipelinesControllerCreate>>>
    export type PipelinesControllerCreateMutationBody = CreatePipelineDto
    export type PipelinesControllerCreateMutationError = unknown
    export type PipelinesControllerCreateMutationVariables = {data: CreatePipelineDto}

    export const usePipelinesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pipelinesControllerCreate>>, TError,PipelinesControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pipelinesControllerCreate>>,
        TError,
        PipelinesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getPipelinesControllerCreateMutationOptions(options), queryClient);
    }

export const stagesControllerCreate = (
    createStageDto: CreateStageDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CreateStageResponseDto>(
      {url: `/v1/stages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStageDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getStagesControllerCreateMutationKey = () => ['stagesControllerCreate'] as const;

export const getStagesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stagesControllerCreate>>, TError,StagesControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof stagesControllerCreate>>, TError,StagesControllerCreateMutationVariables, TContext> => {

const mutationKey = getStagesControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stagesControllerCreate>>, StagesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  stagesControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StagesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof stagesControllerCreate>>>
    export type StagesControllerCreateMutationBody = CreateStageDto
    export type StagesControllerCreateMutationError = unknown
    export type StagesControllerCreateMutationVariables = {data: CreateStageDto}

    export const useStagesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stagesControllerCreate>>, TError,StagesControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stagesControllerCreate>>,
        TError,
        StagesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getStagesControllerCreateMutationOptions(options), queryClient);
    }

export const stagesControllerRename = (
    id: string,
    renameStageDto: RenameStageDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<RenameStageResponseDto>(
      {url: `/v1/stages/${id}/rename`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: renameStageDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getStagesControllerRenameMutationKey = () => ['stagesControllerRename'] as const;

export const getStagesControllerRenameMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stagesControllerRename>>, TError,StagesControllerRenameMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof stagesControllerRename>>, TError,StagesControllerRenameMutationVariables, TContext> => {

const mutationKey = getStagesControllerRenameMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stagesControllerRename>>, StagesControllerRenameMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  stagesControllerRename(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StagesControllerRenameMutationResult = NonNullable<Awaited<ReturnType<typeof stagesControllerRename>>>
    export type StagesControllerRenameMutationBody = RenameStageDto
    export type StagesControllerRenameMutationError = unknown
    export type StagesControllerRenameMutationVariables = {id: string;data: RenameStageDto}

    export const useStagesControllerRename = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stagesControllerRename>>, TError,StagesControllerRenameMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stagesControllerRename>>,
        TError,
        StagesControllerRenameMutationVariables,
        TContext
      > => {
      return useMutation(getStagesControllerRenameMutationOptions(options), queryClient);
    }

export const dealsControllerCreate = (
    createDealDto: CreateDealDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CreateDealResponseDto>(
      {url: `/v1/deals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDealDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getDealsControllerCreateMutationKey = () => ['dealsControllerCreate'] as const;

export const getDealsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerCreate>>, TError,DealsControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dealsControllerCreate>>, TError,DealsControllerCreateMutationVariables, TContext> => {

const mutationKey = getDealsControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dealsControllerCreate>>, DealsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  dealsControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DealsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof dealsControllerCreate>>>
    export type DealsControllerCreateMutationBody = CreateDealDto
    export type DealsControllerCreateMutationError = unknown
    export type DealsControllerCreateMutationVariables = {data: CreateDealDto}

    export const useDealsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerCreate>>, TError,DealsControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dealsControllerCreate>>,
        TError,
        DealsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getDealsControllerCreateMutationOptions(options), queryClient);
    }

export const dealsControllerMove = (
    id: string,
    moveDealDto: MoveDealDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<MoveDealResponseDto>(
      {url: `/v1/deals/${id}/move`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: moveDealDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getDealsControllerMoveMutationKey = () => ['dealsControllerMove'] as const;

export const getDealsControllerMoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerMove>>, TError,DealsControllerMoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dealsControllerMove>>, TError,DealsControllerMoveMutationVariables, TContext> => {

const mutationKey = getDealsControllerMoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dealsControllerMove>>, DealsControllerMoveMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  dealsControllerMove(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DealsControllerMoveMutationResult = NonNullable<Awaited<ReturnType<typeof dealsControllerMove>>>
    export type DealsControllerMoveMutationBody = MoveDealDto
    export type DealsControllerMoveMutationError = unknown
    export type DealsControllerMoveMutationVariables = {id: string;data: MoveDealDto}

    export const useDealsControllerMove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerMove>>, TError,DealsControllerMoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dealsControllerMove>>,
        TError,
        DealsControllerMoveMutationVariables,
        TContext
      > => {
      return useMutation(getDealsControllerMoveMutationOptions(options), queryClient);
    }

export const dealsControllerClose = (
    id: string,
    closeDealDto: CloseDealDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CloseDealResponseDto>(
      {url: `/v1/deals/${id}/close`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: closeDealDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getDealsControllerCloseMutationKey = () => ['dealsControllerClose'] as const;

export const getDealsControllerCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerClose>>, TError,DealsControllerCloseMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof dealsControllerClose>>, TError,DealsControllerCloseMutationVariables, TContext> => {

const mutationKey = getDealsControllerCloseMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dealsControllerClose>>, DealsControllerCloseMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  dealsControllerClose(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DealsControllerCloseMutationResult = NonNullable<Awaited<ReturnType<typeof dealsControllerClose>>>
    export type DealsControllerCloseMutationBody = CloseDealDto
    export type DealsControllerCloseMutationError = unknown
    export type DealsControllerCloseMutationVariables = {id: string;data: CloseDealDto}

    export const useDealsControllerClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dealsControllerClose>>, TError,DealsControllerCloseMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dealsControllerClose>>,
        TError,
        DealsControllerCloseMutationVariables,
        TContext
      > => {
      return useMutation(getDealsControllerCloseMutationOptions(options), queryClient);
    }

export const activitiesControllerCreate = (
    createActivityDto: CreateActivityDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CreateActivityResponseDto>(
      {url: `/v1/activities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createActivityDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getActivitiesControllerCreateMutationKey = () => ['activitiesControllerCreate'] as const;

export const getActivitiesControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerCreate>>, TError,ActivitiesControllerCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerCreate>>, TError,ActivitiesControllerCreateMutationVariables, TContext> => {

const mutationKey = getActivitiesControllerCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activitiesControllerCreate>>, ActivitiesControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  activitiesControllerCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivitiesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof activitiesControllerCreate>>>
    export type ActivitiesControllerCreateMutationBody = CreateActivityDto
    export type ActivitiesControllerCreateMutationError = unknown
    export type ActivitiesControllerCreateMutationVariables = {data: CreateActivityDto}

    export const useActivitiesControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerCreate>>, TError,ActivitiesControllerCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activitiesControllerCreate>>,
        TError,
        ActivitiesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getActivitiesControllerCreateMutationOptions(options), queryClient);
    }

export const activitiesControllerComplete = (
    id: string,
    completeActivityDto: CompleteActivityDto,
 signal?: AbortSignal
) => {


      return sparkHttpClient<CompleteActivityResponseDto>(
      {url: `/v1/activities/${id}/complete`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: completeActivityDto, ...(signal ? { signal }: {})
    },
      );
    }




export const getActivitiesControllerCompleteMutationKey = () => ['activitiesControllerComplete'] as const;

export const getActivitiesControllerCompleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerComplete>>, TError,ActivitiesControllerCompleteMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerComplete>>, TError,ActivitiesControllerCompleteMutationVariables, TContext> => {

const mutationKey = getActivitiesControllerCompleteMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activitiesControllerComplete>>, ActivitiesControllerCompleteMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  activitiesControllerComplete(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ActivitiesControllerCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof activitiesControllerComplete>>>
    export type ActivitiesControllerCompleteMutationBody = CompleteActivityDto
    export type ActivitiesControllerCompleteMutationError = unknown
    export type ActivitiesControllerCompleteMutationVariables = {id: string;data: CompleteActivityDto}

    export const useActivitiesControllerComplete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesControllerComplete>>, TError,ActivitiesControllerCompleteMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activitiesControllerComplete>>,
        TError,
        ActivitiesControllerCompleteMutationVariables,
        TContext
      > => {
      return useMutation(getActivitiesControllerCompleteMutationOptions(options), queryClient);
    }
