import { Body, Controller, Delete, Param, Patch, Post, UseGuards } from "@nestjs/common";
import { ApiBearerAuth, ApiCreatedResponse, ApiOkResponse, ApiTags } from "@nestjs/swagger";
import { discountRuleId, productId } from "@spark/core";
import { CapabilityGuard, CurrentSupabaseUser, RequireCapability, SupabaseJwtGuard, type SupabaseJwtClaims } from "../../../auth/index.js";
import { GetCurrentUserUseCase } from "../../identity/application/get-current-user.usecase.js";
import { CatalogService } from "../application/catalog.service.js";
import { CreateDiscountRuleDto, CreateProductDto, CreateProductVariantDto, DiscountRuleWriteResponseDto, ProductVariantWriteResponseDto, ProductWriteResponseDto, UpdateDiscountRuleDto, UpdateProductDto } from "../dto/catalog.dto.js";
@ApiTags("catalog") @ApiBearerAuth() @UseGuards(SupabaseJwtGuard, CapabilityGuard) @Controller("v1/catalog")
export class CatalogController {
  constructor(private readonly currentUser: GetCurrentUserUseCase, private readonly catalog: CatalogService) {}
  @Post("products") @RequireCapability("catalog:write") @ApiCreatedResponse({ type: ProductWriteResponseDto }) async createProduct(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Body() body: CreateProductDto): Promise<ProductWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.createProduct(user.orgId, body) as Promise<ProductWriteResponseDto>; }
  @Patch("products/:id") @RequireCapability("catalog:write") @ApiOkResponse({ type: ProductWriteResponseDto }) async updateProduct(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Param("id") id: string, @Body() body: UpdateProductDto): Promise<ProductWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.updateProduct(user.orgId, productId.from(id), body) as Promise<ProductWriteResponseDto>; }
  @Delete("products/:id") @RequireCapability("catalog:write") @ApiOkResponse({ type: ProductWriteResponseDto }) async archiveProduct(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Param("id") id: string): Promise<ProductWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.archiveProduct(user.orgId, productId.from(id), true) as Promise<ProductWriteResponseDto>; }
  @Post("products/:id/restore") @RequireCapability("catalog:write") @ApiOkResponse({ type: ProductWriteResponseDto }) async restoreProduct(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Param("id") id: string): Promise<ProductWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.archiveProduct(user.orgId, productId.from(id), false) as Promise<ProductWriteResponseDto>; }
  @Post("variants") @RequireCapability("catalog:write") @ApiCreatedResponse({ type: ProductVariantWriteResponseDto }) async createVariant(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Body() body: CreateProductVariantDto): Promise<ProductVariantWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.createVariant(user.orgId, body) as Promise<ProductVariantWriteResponseDto>; }
  @Post("discount-rules") @RequireCapability("catalog:write") @ApiCreatedResponse({ type: DiscountRuleWriteResponseDto }) async createDiscount(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Body() body: CreateDiscountRuleDto): Promise<DiscountRuleWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.createDiscount(user.orgId, body) as Promise<DiscountRuleWriteResponseDto>; }
  @Patch("discount-rules/:id") @RequireCapability("catalog:write") @ApiOkResponse({ type: DiscountRuleWriteResponseDto }) async updateDiscount(@CurrentSupabaseUser() claims: SupabaseJwtClaims, @Param("id") id: string, @Body() body: UpdateDiscountRuleDto): Promise<DiscountRuleWriteResponseDto> { const user = await this.currentUser.execute(claims.sub); return this.catalog.updateDiscount(user.orgId, discountRuleId.from(id), body) as Promise<DiscountRuleWriteResponseDto>; }
}
